/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;

/**
 *
 * @author vinicius
 */
public class cadastroEmpresa extends javax.swing.JFrame {

    ConnectionConsulta conecta = new ConnectionConsulta();
    /**
     * Creates new form cadastroEmpresa
     */
    public cadastroEmpresa() {
        initComponents();
        preenchertabela("select * from cadastroempresa order by id ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpresa = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButtonAlterar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jButtonExcluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonReset = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCnpj = new javax.swing.JTextField();
        jTextFieldId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldGrupo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableEmpresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpresaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpresa);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_2.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabel16.setText("Salvar");

        jLabel15.setText("Novo");
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 14));

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_1.png"))); // NOI18N
        jButtonAlterar.setToolTipText("Editar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jLabel17.setText("Editar");

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_3.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Deletar");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("Excluir");

        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user3.png"))); // NOI18N
        jButtonReset.setToolTipText("Atualizar");
        jButtonReset.setEnabled(false);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabel18.setText("Atualizar");

        jLabel5.setText("Cadastro Empresa");

        jLabel1.setText("ID:");

        jLabel2.setText("Código:");

        jLabel4.setText("CNPJ:");

        jLabel3.setText("Empresa:");

        jTextFieldId.setEnabled(false);

        jLabel7.setText("Grupo:");

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonNovo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonAlterar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonExcluir, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonReset, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldCodigo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldCnpj, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldId, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldGrupo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229)
                        .addComponent(jLabel5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(jTextFieldGrupo))
                        .addGap(28, 28, 28)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(32, 32, 32)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(34, 34, 34)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel18)))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonNovo))
                            .addComponent(jButtonReset))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel6)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(740, 421));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpresaMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableEmpresa.getValueAt(jTableEmpresa.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from cadastroempresa where id='"+ id +"'");

        try {
            conecta.rs.first();
            jTextFieldId.setText(String.valueOf(conecta.rs.getInt("id")));
            jTextFieldCodigo.setText(conecta.rs.getString("Código"));
            jTextFieldEmpresa.setText(conecta.rs.getString("Empresa"));
            jTextFieldCnpj.setText(conecta.rs.getString("CNPJ"));
            jTextFieldGrupo.setText(conecta.rs.getString("Grupo"));

             jButtonSalvar.setEnabled(true);
             jButtonAlterar.setEnabled(true);
             jButtonExcluir.setEnabled(true);
//            jTextFieldLogin.setEnabled(true);
//            jTextFieldNome.setEnabled(true);
//            jComboBoxPermissao.setEnabled(true);
//            jComboBoxPermissao2.setEnabled(true);
//            jComboBoxDest1.setEnabled(true);
//            jComboBoxDest2.setEnabled(true);
//            jComboBoxDepart.setEnabled(true);
//            jPasswordFieldSenha1.setEnabled(true);
//            jPasswordFieldConfSenha1.setEnabled(true);
//            jPasswordFieldConfSenha1.setEnabled(true);
//            jPasswordFieldSenha1.setEnabled(true);
            
            //        jButtonAlterar.setEnabled(true);
            
            //        jTextFieldEmpresa.setEnabled(true);
            //        jTextFieldDescricao.setEnabled(true);
            //        jComboBoxDestinatario.setEnabled(true);
            //        jComboBoxDepartamento.setEnabled(true);
            //        jTextFieldData.setEnabled(false);
            //        jTextFieldDataEntrega.setEnabled(false);
            //        jTextFieldHorario.setEnabled(false);
            //        jComboBoxEntrega.setEnabled(true);
            //        jComboBoxCorreios.setEnabled(true);
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableEmpresaMouseClicked

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldCodigo.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha um código!");}
        else{if(jTextFieldEmpresa.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo Empresa!");}
            else{if(jTextFieldCnpj.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo CNPJ!");}
            else{if(jTextFieldGrupo.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo Grupo!");}
                else{
                    try{
                        conecta.conectaBanco();
                        PreparedStatement pst = conecta.conn.prepareStatement("insert into cadastroempresa (código,empresa,cnpj,Grupo)values (?,?,?,?)");
                        pst.setString(1,jTextFieldCodigo.getText());
                        pst.setString(2,jTextFieldEmpresa.getText());
                        pst.setString(3,jTextFieldCnpj.getText());
                        pst.setString(4,jTextFieldGrupo.getText());
                        pst.executeUpdate();
                        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
                        //preenchertabela("select * from usuarios order by id");
                        preenchertabela("select * from cadastroempresa order by id ");
                        conecta.desconecta();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
                    }
//                    try{
//                        SimpleEmail emailSimples = new SimpleEmail();
//                        emailSimples.setHostName("200.170.82.150");
//                        emailSimples.setSmtpPort(587);
//                        emailSimples.setFrom(jTextFieldEmail.getText(),jTextFieldEmail.getText());
//                        emailSimples.addTo(jTextFieldEmail.getText());
//                        emailSimples.setSubject(jLabelsubject.getText());
//                        emailSimples.setMsg(jTextFieldDescricao.getText());
//                        emailSimples.setAuthentication("tecnologia@asscont.com.br","Asscont1000");
//                        emailSimples.send();
//                        JOptionPane.showMessageDialog(null, "Mensagem enviada");
//                    } catch (EmailException ex) {

                    //}
                    jTextFieldId.setText("");
                    jTextFieldCodigo.setText("");
                    jTextFieldEmpresa.setText("");
                    jTextFieldCnpj.setText("");
                   // jTextFieldEmpresa.setEnabled(false);
                   // jTextFieldDescricao.setEnabled(false);
                   // jComboBoxDestinatario.setEnabled(false);
                  //  jComboBoxDepartamento.setEnabled(false);
                  //  jTextFieldData.setEnabled(false);
                  //  jTextFieldDataEntrega.setEnabled(false);
                  //  jTextFieldHorario.setEnabled(false);
                  //  jComboBoxEntrega.setEnabled(false);
                   // jComboBoxCorreios.setEnabled(false);
                    jButtonAlterar.setEnabled(false);
                    jButtonExcluir.setEnabled(false);
                    jButtonSalvar.setEnabled(false);
                    jButtonNovo.setEnabled(true);

                }
            }
        }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update cadastroempresa set código= ?, empresa=?, cnpj=?, grupo=? where id=?");
            pst.setString(1,jTextFieldCodigo.getText());
            pst.setString(2,jTextFieldEmpresa.getText());
            pst.setString(3,jTextFieldCnpj.getText());
            pst.setString(4,jTextFieldGrupo.getText());
            pst.setInt(5,Integer.parseInt(jTextFieldId.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
            preenchertabela("select * from cadastroempresa order by id ");
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //       conecta.executaSQL("delete from usuario where empresa='"+jTextFieldEmpresa.getText()+"'");
        //        JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso");
        try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("delete from cadastroempresa where id= ?");
            pst.setString(1,jTextFieldId.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso");
            //preenchertabela("select * from usuarios order by id");
            preenchertabela("select * from cadastroempresa order by id ");
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao excluir!\n Erro: "+ex);
        }
//        jTextFieldCod.setText("");
//        jTextFieldEmpresa.setText("");
//        jTextFieldDescricao.setText("");
//        jComboBoxDestinatario.setSelectedItem("");
//        jComboBoxDepartamento.setSelectedItem("");
//        jTextFieldData.setText("");
//        jTextFieldDataEntrega.setText("");
//        jTextFieldHorario.setText("");
//        jTextFieldEmpresa.setEnabled(false);
//        jTextFieldDescricao.setEnabled(false);
//        jComboBoxDestinatario.setEnabled(false);
//        jComboBoxDepartamento.setEnabled(false);
//        jTextFieldData.setEnabled(false);
//        jTextFieldDataEntrega.setEnabled(false);
//        jTextFieldHorario.setEnabled(false);
//        jButtonAlterar.setEnabled(false);
//        jButtonExcluir.setEnabled(false);
//        jButtonSalvar.setEnabled(false);
//        jButtonNovo.setEnabled(true);
                    jTextFieldId.setText("");
                    jTextFieldCodigo.setText("");
                    jTextFieldEmpresa.setText("");
                    jTextFieldCnpj.setText("");
                   
                    jButtonAlterar.setEnabled(false);
                    jButtonExcluir.setEnabled(false);
                    jButtonSalvar.setEnabled(false);
                    jButtonNovo.setEnabled(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldId.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldCnpj.setText("");
      
//        jButtonAlterar.setEnabled(false);
//        jButtonExcluir.setEnabled(false);
//        jTextFieldEmpresa.setEnabled(false);
//        jTextFieldDescricao.setEnabled(false);
//        jComboBoxDestinatario.setEnabled(false);
//        jComboBoxDepartamento.setEnabled(false);
//        jTextFieldData.setEnabled(false);
//        jTextFieldDataEntrega.setEnabled(false);
//        jTextFieldHorario.setEnabled(false);
//        jButtonSalvar.setEnabled(false);
//        jComboBoxEntrega.setEnabled(false);
//        jComboBoxCorreios.setEnabled(false);
        //preenchertabela("select * from usuarios order by id");
        preenchertabela("select * from cadastroempresa order by id ");

    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        // modelo = control.Primeiro();
        jTextFieldId.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldCnpj.setText("");
        jTextFieldGrupo.setText("");
//        jTextFieldDescricao.setText("");
//        jComboBoxDestinatario.setSelectedItem("Sem seleção");
//        jComboBoxDepartamento.setSelectedItem("Sem seleção");
//        jTextFieldData.setText("");
//        jTextFieldDataEntrega.setText("");
//        jTextFieldHorario.setText("");
//        jComboBoxEntrega.setSelectedItem("entregue");
        //jTextField1log.setText("");
//        jComboBoxRecebimento.setSelectedItem("Não recebido");
//        jComboBoxCorreios.setSelectedItem("Malote");
//        jTextField1.setText("Aguardando");
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldCnpj.setEnabled(true);
        jTextFieldGrupo.setEnabled(true);
//        jTextFieldDescricao.setEnabled(true);
//        jComboBoxDestinatario.setEnabled(true);
//        jComboBoxDepartamento.setEnabled(true);
//        jTextFieldData.setEnabled(false);
//        jTextFieldDataEntrega.setEnabled(true);
//        jTextFieldHorario.setEnabled(false);
//        jComboBoxEntrega.setEnabled(true);
//        jComboBoxCorreios.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonReset.setEnabled(true);
        //jTextFieldPesquisar.setEnabled(true);
        //jButtonPesquisar.setEnabled(true);
        //  jTextField1log.setText(modelo.getLogin());
        //preenchertabela("select * from usuarios order by id");
        // enviatexto.setState(Consultador.NORMAL);
        //  enviatexto.recebendo(jTextField1log.getText());
      //  conecta.conectaBanco();
    //    preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
      //  conecta.desconecta();
    }//GEN-LAST:event_jButtonNovoActionPerformed
public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","CÓDIGO","EMPRESA","CNPJ","GRUPO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
          //  conecta.conectaBanco();
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("código"),conecta.rs.getString("empresa"),conecta.rs.getString("cnpj"),conecta.rs.getString("grupo")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
       //     JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableEmpresa.setModel(modelo);
        jTableEmpresa.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableEmpresa.getColumnModel().getColumn(0).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(1).setPreferredWidth(70);
        jTableEmpresa.getColumnModel().getColumn(1).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableEmpresa.getColumnModel().getColumn(2).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(3).setPreferredWidth(160);
        jTableEmpresa.getColumnModel().getColumn(3).setResizable(false);
        jTableEmpresa.getColumnModel().getColumn(4).setPreferredWidth(160);
        jTableEmpresa.getColumnModel().getColumn(4).setResizable(false);
        jTableEmpresa.getTableHeader().setReorderingAllowed(true);
        jTableEmpresa.setAutoResizeMode(jTableEmpresa.AUTO_RESIZE_OFF);
        jTableEmpresa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroEmpresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroEmpresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpresa;
    private javax.swing.JTextField jTextFieldCnpj;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JTextField jTextFieldGrupo;
    private javax.swing.JTextField jTextFieldId;
    // End of variables declaration//GEN-END:variables
}
