/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.*;
import controle.AtualizaDia;
import controle.AtualizadoHora;
import controle.ConnectionConsulta;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloTabela;
import modelo.ModeloTabela;

/**
 *
 * @author vinicius
 */
public class ConfirmacaoRecebimentoRecepcao extends javax.swing.JFrame {

    ConnectionConsulta conecta = new ConnectionConsulta();

    /**
     * Creates new form ConfirmacaoRecebimento
     */
      int flag=1;
    public ConfirmacaoRecebimentoRecepcao() {
        initComponents();
      //  conecta.conectaBanco();
       //preenchertabela("select * from usuarios where destinatario = 'TDP' and recebimento = 'Não recebido' order by id");
       // preenchertabela("select * from login,usuarios where login ='" + jTextFieldBaixa.getText()+"' and area = '?' and departamento ='?' ");
        AtualizadoHora.start(jLabelHorario);  
        AtualizaDia.start(jLabelDia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecebimento = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldEmp = new javax.swing.JTextField();
        jTextFieldDesc = new javax.swing.JTextField();
        jTextFieldDest = new javax.swing.JTextField();
        jTextFieldDepar = new javax.swing.JTextField();
        jTextFieldData = new javax.swing.JTextField();
        jComboBoxRec = new javax.swing.JComboBox<>();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonAlterar = new javax.swing.JButton();
        jFormattedTextFieldDataEntrega = new javax.swing.JFormattedTextField();
        jFormattedTextFieldHorario = new javax.swing.JFormattedTextField();
        jComboBoxEntrega = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButtonTodos1 = new javax.swing.JButton();
        jTextFieldBaixa = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelDia = new javax.swing.JLabel();
        jLabelHorario = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldProtocolo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableRecebimento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableRecebimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableRecebimentoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableRecebimento);

        jLabel1.setText("Código:");

        jLabel2.setText("Empresa:");

        jLabel3.setText("Descrição:");

        jLabel4.setText("Destinatário:");

        jLabel5.setText("Departamento:");

        jLabel6.setText("Data:");

        jLabel7.setText("Data entrega:");

        jLabel8.setText("Horário:");

        jLabel9.setText("Recebimento:");

        jLabel10.setText("Usuário:");

        jTextFieldCod.setEnabled(false);

        jTextFieldEmp.setEnabled(false);

        jTextFieldDesc.setEnabled(false);

        jTextFieldDest.setEnabled(false);

        jTextFieldDepar.setEnabled(false);

        jTextFieldData.setEnabled(false);

        jComboBoxRec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não recebido", "Recebido" }));
        jComboBoxRec.setEnabled(false);
        jComboBoxRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRecActionPerformed(evt);
            }
        });

        jTextFieldUsuario.setEnabled(false);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_1.png"))); // NOI18N
        jButtonAlterar.setToolTipText("");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDataEntrega.setEnabled(false);
        jFormattedTextFieldDataEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldDataEntregaActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldHorario.setEnabled(false);

        jComboBoxEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não entregue", "entregue" }));
        jComboBoxEntrega.setToolTipText("");
        jComboBoxEntrega.setEnabled(false);
        jComboBoxEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEntregaActionPerformed(evt);
            }
        });

        jLabel12.setText("Entrega:");

        jButtonTodos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Todos.png"))); // NOI18N
        jButtonTodos1.setToolTipText("");
        jButtonTodos1.setEnabled(false);
        jButtonTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodos1ActionPerformed(evt);
            }
        });

        jTextFieldBaixa.setEditable(false);
        jTextFieldBaixa.setEnabled(false);

        jLabel11.setText("Baixa:");

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabelDia.setText("jLabel13");

        jLabelHorario.setText("jLabel14");

        jLabel15.setText("Data Baixa:");

        jLabel16.setText("Horário Baixa:");

        jLabel13.setText("Receber selecionado");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Receber todos");

        jLabel17.setText("Protocolo:");

        jTextFieldProtocolo.setEnabled(false);

        jLabel18.setText("Tipo:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correio", "Malote" }));
        jComboBoxTipo.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jLabel13)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(jButtonTodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14))))
                            .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelHorario)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxRec, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldProtocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jFormattedTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTodos1)
                            .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(jComboBoxEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jComboBoxRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelHorario)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(jLabelDia))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1285, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableRecebimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableRecebimentoMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableRecebimento.getValueAt(jTableRecebimento.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from enviorecepcao where id='"+ id +"'");
        
        try {
        conecta.rs.first();
        jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
        jTextFieldProtocolo.setText(conecta.rs.getString("protocolo"));
        jTextFieldEmp.setText(conecta.rs.getString("empresa"));
        jTextFieldDesc.setText(conecta.rs.getString("descricao"));
        jTextFieldDest.setText(conecta.rs.getString("destinatario"));
        jTextFieldDepar.setText(conecta.rs.getString("departamento"));
        jTextFieldData.setText(conecta.rs.getString("data"));
        jFormattedTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));
        jFormattedTextFieldHorario.setText(conecta.rs.getString("horario"));   
        jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
        jTextFieldUsuario.setText(conecta.rs.getString("usuario")); 
        jComboBoxRec.setSelectedItem(conecta.rs.getString("recebimento"));
        jComboBoxTipo.setSelectedItem(conecta.rs.getString("tipo"));
       // jTextFieldBaixa.setText("Talita");
        jButtonAlterar.setEnabled(true);
        jButtonTodos1.setEnabled(true);
        jComboBoxRec.setEnabled(false);
        jComboBoxEntrega.setEnabled(false);
        jFormattedTextFieldDataEntrega.setEnabled(false);
        jFormattedTextFieldHorario.setEnabled(false);
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);          
        }
    }//GEN-LAST:event_jTableRecebimentoMouseClicked

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update enviorecepcao set protocolo=?, empresa=?, descricao=?, destinatario=?, departamento=?, data=?, dataentrega=?, horario=?, entrega=?, recebimento='Recebido', baixa=?, diabaixa=?, horariobaixa=? where id=?");
            pst.setString(1,jTextFieldProtocolo.getText());
            pst.setString(2,jTextFieldEmp.getText());
            pst.setString(3,jTextFieldDesc.getText());
            pst.setString(4,jTextFieldDest.getText());
            pst.setString(5,jTextFieldDepar.getText());
            pst.setString(6,jTextFieldData.getText());
            pst.setString(7,jFormattedTextFieldDataEntrega.getText());
            pst.setString(8,jFormattedTextFieldHorario.getText());
            pst.setString(9, (String) jComboBoxEntrega.getSelectedItem());
           // pst.setString(9, (String) jComboBoxRec.getSelectedItem());
            pst.setString(10, jTextFieldBaixa.getText());
            pst.setString(11, jLabelDia.getText());
            pst.setString(12, jLabelHorario.getText());
            pst.setInt(13,Integer.parseInt(jTextFieldCod.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            preenchertabela("select enviorecepcao.* from enviorecepcao INNER JOIN login on enviorecepcao.destinatario = login.area where login = '" + jTextFieldBaixa.getText()+"' and recebimento = 'Não recebido' order by id");
            
            jTextFieldCod.setText("");
            jTextFieldEmp.setText("");
            jTextFieldDesc.setText("");
            jTextFieldDest.setText("");
            jTextFieldDepar.setText("");
            jTextFieldData.setText("");
            jFormattedTextFieldDataEntrega.setText("");
            jFormattedTextFieldHorario.setText("");
            jComboBoxRec.setSelectedItem("");
            jComboBoxEntrega.setSelectedItem("");
            jTextFieldUsuario.setText("");
           // jTextFieldBaixa.setText("");
            jButtonAlterar.setEnabled(false);
            jComboBoxRec.setEnabled(false);
            jComboBoxEntrega.setEnabled(false);
            conecta.desconecta();
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
           }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jComboBoxRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRecActionPerformed

    private void jFormattedTextFieldDataEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldDataEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldDataEntregaActionPerformed

    private void jComboBoxEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEntregaActionPerformed

    private void jButtonTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodos1ActionPerformed
        // TODO add your handling code here:         
   try {
       conecta.conectaBanco();
       PreparedStatement pst = conecta.conn.prepareStatement("update enviorecepcao set recebimento='Recebido', baixa=?, diabaixa=?, horariobaixa=? where recebimento='Não recebido' and destinatario =?");
            
            pst.setString(1,jTextFieldBaixa.getText());
            pst.setString(2, jLabelDia.getText());
            pst.setString(3, jLabelHorario.getText());
            pst.setString(4,jTextFieldDest.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            preenchertabela("select usuarios.* from usuarios INNER JOIN login on usuarios.destinatario = login.area where login = '" + jTextFieldBaixa.getText()+"' and recebimento = 'Não recebido' order by id");
            
            jTextFieldCod.setText("");
            jTextFieldEmp.setText("");
            jTextFieldDesc.setText("");
            jTextFieldDest.setText("");
            jTextFieldDepar.setText("");
            jTextFieldData.setText("");
            jFormattedTextFieldDataEntrega.setText("");
            jFormattedTextFieldHorario.setText("");
            jComboBoxRec.setSelectedItem("");
            jComboBoxEntrega.setSelectedItem("");
            jTextFieldUsuario.setText("");
            jButtonAlterar.setEnabled(false);
            jButtonTodos1.setEnabled(false);
            jComboBoxRec.setEnabled(false);
            jComboBoxEntrega.setEnabled(false);
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
            
           }

    }//GEN-LAST:event_jButtonTodos1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       conecta.conectaBanco();
       preenchertabela("select enviorecepcao.* from enviorecepcao INNER JOIN login on enviorecepcao.destinatario = login.area || enviorecepcao.destinatario = login.subarea || enviorecepcao.departamento = login.depart where login = '" + jTextFieldBaixa.getText()+"' and recebimento = 'Não recebido' order by id");
       conecta.desconecta();
    }//GEN-LAST:event_jButton1ActionPerformed

    
       public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","PROTOCOLO","EMPRESA","DESCRICAO","DESTINATARIO","DEPARTAMENTO","DATA","DATAENTREGA","HORARIO","USUARIO","ENTREGA","RECEBIMENTO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first(); 
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("protocolo"),conecta.rs.getString("empresa"),conecta.rs.getString("descricao"),conecta.rs.getString("destinatario"),conecta.rs.getString("departamento"),conecta.rs.getString("data"),conecta.rs.getString("dataentrega"),conecta.rs.getString("horario"),conecta.rs.getString("usuario"),conecta.rs.getString("entrega"),conecta.rs.getString("recebimento")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
            jButtonAlterar.setEnabled(false);
        }
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableRecebimento.setModel(modelo);
        jTableRecebimento.getColumnModel().getColumn(0).setPreferredWidth(48);
        jTableRecebimento.getColumnModel().getColumn(0).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(1).setPreferredWidth(48);
        jTableRecebimento.getColumnModel().getColumn(1).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(2).setPreferredWidth(220);
        jTableRecebimento.getColumnModel().getColumn(2).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(3).setPreferredWidth(375);
        jTableRecebimento.getColumnModel().getColumn(3).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(4).setPreferredWidth(96);
        jTableRecebimento.getColumnModel().getColumn(4).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTableRecebimento.getColumnModel().getColumn(5).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(6).setPreferredWidth(75);
        jTableRecebimento.getColumnModel().getColumn(6).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(7).setPreferredWidth(100);
        jTableRecebimento.getColumnModel().getColumn(7).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(8).setPreferredWidth(65);
        jTableRecebimento.getColumnModel().getColumn(8).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(9).setPreferredWidth(66);
        jTableRecebimento.getColumnModel().getColumn(9).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(10).setPreferredWidth(73);
        jTableRecebimento.getColumnModel().getColumn(10).setResizable(false);
        jTableRecebimento.getColumnModel().getColumn(11).setPreferredWidth(97);
        jTableRecebimento.getColumnModel().getColumn(11).setResizable(false);
        jTableRecebimento.getTableHeader().setReorderingAllowed(false);
        jTableRecebimento.setAutoResizeMode(jTableRecebimento.AUTO_RESIZE_OFF);
        jTableRecebimento.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoRecebimentoRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoRecebimentoRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoRecebimentoRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmacaoRecebimentoRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmacaoRecebimentoRecepcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonTodos1;
    private javax.swing.JComboBox<String> jComboBoxEntrega;
    private javax.swing.JComboBox<String> jComboBoxRec;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataEntrega;
    private javax.swing.JFormattedTextField jFormattedTextFieldHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableRecebimento;
    private javax.swing.JTextField jTextFieldBaixa;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldDepar;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldDest;
    private javax.swing.JTextField jTextFieldEmp;
    private javax.swing.JTextField jTextFieldProtocolo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
  public void recebendo(String recebe){
        jTextFieldBaixa.setText(recebe);
    }
}
