/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import com.mxrck.autocompleter.TextAutoCompleter;
import controle.AtualizaDia;
import controle.AtualizadoHora;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import controle.conectar;
import java.sql.Connection;
import modelo.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import modelo.ModeloLoginUsuario;
import modelo.Usuario;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;


/**
 *
 * @author vinicius
 */
public class Consultador extends javax.swing.JFrame {
    
    ConnectionConsulta conecta = new ConnectionConsulta();
    Usuario mod = new Usuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();
    Consultador enviatexto;
    /**
     * Creates new form Consultador
     */
    public Consultador() {
        initComponents();
        items();
        itemm();
       // conecta.conectaBanco();
     //  preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id");
        //preenchertabela("select * from usuarios order by id");
        AtualizadoHora.start(jLabelHorario);  
        AtualizaDia.start(jLabelDia);
       
    }

    public void items (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldEmpresa);
        conecta.conectaBanco();
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT Empresa from cadastroempresa"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("Empresa"));
            }
           conecta.desconecta();
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }

        public void itemm (){
        
        TextAutoCompleter textAutoAcompleter = new TextAutoCompleter( jTextFieldDescricao);
        conecta.conectaBanco();
        Connection minhaconexao = conectar.GetConnection();
        
        Statement st=null;
        ResultSet rs=null;
        
        try{
            st = (Statement)minhaconexao.createStatement();
            rs=st.executeQuery("SELECT DISTINCT descricao from usuarios"); 
            
            while (rs.next()){
                textAutoAcompleter.addItem(rs.getString("descricao"));
            }
            conecta.desconecta();
        }catch(Exception de)
        {
          JOptionPane.showMessageDialog(this, de.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEmpresa = new javax.swing.JTextField();
        jTextFieldDescricao = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JFormattedTextField();
        jTextFieldDataEntrega = new javax.swing.JFormattedTextField();
        jTextFieldHorario = new javax.swing.JFormattedTextField();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JFormattedTextField();
        jLabelHorario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1log = new javax.swing.JTextField();
        jComboBoxRecebimento = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxDestinatario = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxEntrega = new javax.swing.JComboBox<>();
        jButtonReset = new javax.swing.JButton();
        jComboBoxDepartamento = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxCorreios = new javax.swing.JComboBox<>();
        jLabelDia = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldDiaBaixa = new javax.swing.JTextField();
        jTextFieldHorarioBaixa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabelsubject = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEstado.setOpaque(false);
        jTableEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstado);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciador"));

        jLabel3.setText("Código:");

        jLabel4.setText("Empresa:");

        jLabel5.setText("Data:");

        jLabel6.setText("Descrição:");

        jLabel7.setText("Destinatario:");

        jLabel8.setText("Departamento:");

        jLabel9.setText("Data de Entrega:");

        jLabel10.setText("Horario:");

        jTextFieldEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldEmpresa.setEnabled(false);
        jTextFieldEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpresaActionPerformed(evt);
            }
        });

        jTextFieldDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDescricao.setEnabled(false);

        jTextFieldCod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user.png"))); // NOI18N
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_2.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_1.png"))); // NOI18N
        jButtonAlterar.setToolTipText("Editar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_3.png"))); // NOI18N
        jButtonExcluir.setToolTipText("Deletar");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/error.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        try {
            jTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldData.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldData.setEnabled(false);
        jTextFieldData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataActionPerformed(evt);
            }
        });

        try {
            jTextFieldDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldDataEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDataEntrega.setEnabled(false);

        try {
            jTextFieldHorario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldHorario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldHorario.setEnabled(false);

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/previous.png"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.setEnabled(false);
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/skip.png"))); // NOI18N
        jButtonUltimo.setToolTipText("Ultimo");
        jButtonUltimo.setEnabled(false);
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/left-arrow.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.setEnabled(false);
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/right-arrow.png"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.setEnabled(false);
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar data");
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setEnabled(false);
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        try {
            jTextFieldPesquisar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldPesquisar.setEnabled(false);
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });

        jLabelHorario.setText("jLabel2");

        jLabel2.setText("Tipo:");

        jTextField1log.setEnabled(false);
        jTextField1log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1logActionPerformed(evt);
            }
        });

        jComboBoxRecebimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não recebido", "Recebido" }));
        jComboBoxRecebimento.setEnabled(false);
        jComboBoxRecebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxRecebimentoActionPerformed(evt);
            }
        });

        jLabel11.setText("Recebimento:");

        jComboBoxDestinatario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "AC", "Adriana", "Andreia", "Bruno", "Edilene", "Gustavo", "Jurídico", "Katia", "RH", "TDP", "Declarações", "Financeiro" }));
        jComboBoxDestinatario.setEnabled(false);
        jComboBoxDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDestinatarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Entrega:");

        jComboBoxEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "entregue", "Não entregue" }));
        jComboBoxEntrega.setToolTipText("");
        jComboBoxEntrega.setEnabled(false);
        jComboBoxEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEntregaActionPerformed(evt);
            }
        });

        jButtonReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user3.png"))); // NOI18N
        jButtonReset.setToolTipText("Atualizar");
        jButtonReset.setEnabled(false);
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jComboBoxDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Contábil", "Contábil", "Contábil", "Fiscal", "Contábil", "Contábil", "Fiscal", "Contábil", "Jurídico", "Contábil", "RH", "DP", "Declarações", "Financeiro" }));
        jComboBoxDepartamento.setToolTipText("");
        jComboBoxDepartamento.setEnabled(false);
        jComboBoxDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDepartamentoActionPerformed(evt);
            }
        });

        jLabel13.setText("Usuário:");

        jComboBoxCorreios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malote", "Correio" }));
        jComboBoxCorreios.setEnabled(false);
        jComboBoxCorreios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorreiosActionPerformed(evt);
            }
        });

        jLabelDia.setText("jLabel14");

        jTextFieldEmail.setEditable(false);
        jTextFieldEmail.setToolTipText("");
        jTextFieldEmail.setEnabled(false);

        jLabel14.setText("E-mail:");

        jLabel15.setText("Novo");
        jLabel15.setPreferredSize(new java.awt.Dimension(20, 14));

        jLabel16.setText("Salvar");

        jLabel17.setText("Editar");

        jLabel18.setText("Atualizar");

        jLabel19.setText("Sair");

        jTextFieldDiaBaixa.setEditable(false);
        jTextFieldDiaBaixa.setText("Aguardando");
        jTextFieldDiaBaixa.setEnabled(false);

        jTextFieldHorarioBaixa.setEditable(false);
        jTextFieldHorarioBaixa.setText("Aguardando");
        jTextFieldHorarioBaixa.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabelHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBoxEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonPrimeiro)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonUltimo)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAnterior)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonProximo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel6))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDescricao)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(11, 11, 11)
                                                .addComponent(jLabel2)
                                                .addGap(17, 17, 17))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(25, 25, 25)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jLabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldDiaBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jComboBoxCorreios, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel13)))
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextField1log, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(24, 24, 24)
                                                        .addComponent(jTextFieldHorarioBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                        .addGap(0, 50, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonPesquisar)))
                        .addGap(3, 3, 3)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDia)
                            .addComponent(jTextFieldDiaBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHorarioBaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelHorario)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField1log, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxRecebimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jComboBoxEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jComboBoxCorreios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPrimeiro)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButtonNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jButtonUltimo)
                                    .addComponent(jButtonAnterior)
                                    .addComponent(jButtonProximo)
                                    .addComponent(jButtonReset)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonPesquisar)
                        .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel18))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Formulario");

        jTextField1.setText("jTextField1");

        jLabelsubject.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(554, 554, 554)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(600, 600, 600)
                    .addComponent(jLabelsubject)
                    .addGap(600, 600, 600)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(637, 637, 637)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(638, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(283, 283, 283)
                    .addComponent(jLabelsubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(283, 283, 283)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(283, Short.MAX_VALUE)))
        );

        setSize(new java.awt.Dimension(1350, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
       // modelo = control.Primeiro();
        jTextFieldCod.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldDescricao.setText("");
        jComboBoxDestinatario.setSelectedItem("Sem seleção");
        jComboBoxDepartamento.setSelectedItem("Sem seleção");
        jTextFieldData.setText("");
        jTextFieldDataEntrega.setText("");
        jTextFieldHorario.setText("");
        jComboBoxEntrega.setSelectedItem("entregue");
        //jTextField1log.setText("");
        jComboBoxRecebimento.setSelectedItem("Não recebido");
        jComboBoxCorreios.setSelectedItem("Malote");
        jTextField1.setText("Aguardando");
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(false);
        jTextFieldDataEntrega.setEnabled(true);
        jTextFieldHorario.setEnabled(false);
        jComboBoxEntrega.setEnabled(true);
        jComboBoxCorreios.setEnabled(true);
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonReset.setEnabled(true);
        //jTextFieldPesquisar.setEnabled(true);
        //jButtonPesquisar.setEnabled(true);
      //  jTextField1log.setText(modelo.getLogin());
       //preenchertabela("select * from usuarios order by id");
        // enviatexto.setState(Consultador.NORMAL);
       //  enviatexto.recebendo(jTextField1log.getText());
       conecta.conectaBanco();
      preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
                conecta.desconecta(); 
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
if(jComboBoxDestinatario.getSelectedItem().equals("Sem seleção")){JOptionPane.showMessageDialog(null,"Selecione um destinatario!");}
else{if(jTextFieldEmpresa.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo Empresa!");}
else{if(jTextFieldDescricao.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha o campo Descrição!");}
else{
        try{
            conecta.conectaBanco();
        PreparedStatement pst = conecta.conn.prepareStatement("insert into usuarios (empresa,descricao,destinatario,departamento,data,dataentrega,horario,entrega,usuario,recebimento,correio,baixa,diabaixa,horariobaixa)values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        pst.setString(1,jTextFieldEmpresa.getText());
        pst.setString(2,jTextFieldDescricao.getText());
        pst.setString(3, (String) jComboBoxDestinatario.getSelectedItem());
        pst.setString(4, (String) jComboBoxDepartamento.getSelectedItem());
        pst.setString(5,jLabelDia.getText());
        pst.setString(6,jTextFieldDataEntrega.getText());
        pst.setString(7,jLabelHorario.getText());
        pst.setString(8,(String) jComboBoxEntrega.getSelectedItem());
        pst.setString(9,jTextField1log.getText());
        pst.setString(10, (String) jComboBoxRecebimento.getSelectedItem());
        pst.setString(11, (String) jComboBoxCorreios.getSelectedItem());
        pst.setString(12, (String)jTextField1.getText());
        pst.setString(13,jTextFieldDiaBaixa.getText());
        pst.setString(14,jTextFieldHorarioBaixa.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
        //preenchertabela("select * from usuarios order by id");
        preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
       conecta.desconecta(); 
        } catch (SQLException ex) {                        
            JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
        }
         try{
            SimpleEmail emailSimples = new SimpleEmail();
            emailSimples.setHostName("200.170.82.150");
            emailSimples.setSmtpPort(587);
            emailSimples.setFrom(jTextFieldEmail.getText(),jTextFieldEmail.getText());          
            emailSimples.addTo(jTextFieldEmail.getText());
            emailSimples.setSubject(jLabelsubject.getText());
            emailSimples.setMsg(jTextFieldDescricao.getText());  
            emailSimples.setAuthentication("tecnologia@asscont.com.br","Asscont1000");
            emailSimples.send();  
            JOptionPane.showMessageDialog(null, "Mensagem enviada");
        } catch (EmailException ex) {
            
        }
        jTextFieldCod.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldDescricao.setText("");
        jComboBoxDestinatario.setSelectedItem("");
        jComboBoxDepartamento.setSelectedItem("");
        jTextFieldData.setText("");
        jTextFieldDataEntrega.setText("");
        jTextFieldHorario.setText("");
        jComboBoxEntrega.setSelectedItem("");
        jComboBoxCorreios.setSelectedItem("");
        jTextFieldEmpresa.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jComboBoxDestinatario.setEnabled(false);
        jComboBoxDepartamento.setEnabled(false);
        jTextFieldData.setEnabled(false);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxEntrega.setEnabled(false);
        jComboBoxCorreios.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        
}
}
}
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        //       conecta.executaSQL("delete from usuario where empresa='"+jTextFieldEmpresa.getText()+"'");
//        JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso");       
        try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("delete from usuarios where id= ?");
            pst.setString(1,jTextFieldCod.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Excluido com sucesso");
            //preenchertabela("select * from usuarios order by id");
            preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
            conecta.desconecta(); 
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao excluir!\n Erro: "+ex);
        }
        jTextFieldCod.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldDescricao.setText("");
        jComboBoxDestinatario.setSelectedItem("");
        jComboBoxDepartamento.setSelectedItem("");
        jTextFieldData.setText("");
        jTextFieldDataEntrega.setText("");
        jTextFieldHorario.setText("");
        jTextFieldEmpresa.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jComboBoxDestinatario.setEnabled(false);
        jComboBoxDepartamento.setEnabled(false);
        jTextFieldData.setEnabled(false);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonNovo.setEnabled(true);
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTextFieldEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpresaActionPerformed

    private void jTextFieldDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDataActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update usuarios set empresa= ?, descricao=?, destinatario=?, departamento=?, data=?, dataentrega=?, horario=?, entrega=?, usuario=?, recebimento=?, correio=? where id=?");
            pst.setString(1,jTextFieldEmpresa.getText());
            pst.setString(2,jTextFieldDescricao.getText());
            pst.setString(3, (String) jComboBoxDestinatario.getSelectedItem());
            pst.setString(4, (String) jComboBoxDepartamento.getSelectedItem());
            pst.setString(5,jTextFieldData.getText());
            pst.setString(6,jTextFieldDataEntrega.getText());
            pst.setString(7,jTextFieldHorario.getText());
            pst.setString(8,(String) jComboBoxEntrega.getSelectedItem());
            pst.setString(9,jTextField1log.getText());
            pst.setString(10, (String) jComboBoxRecebimento.getSelectedItem());
            pst.setString(11, (String) jComboBoxCorreios.getSelectedItem());
            pst.setInt(12,Integer.parseInt(jTextFieldCod.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
            preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(true);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxEntrega.setEnabled(true);
        jComboBoxCorreios.setEnabled(true);
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios");
            conecta.rs.first();
            jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
            jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
            jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
            jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
            jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
            jTextFieldData.setText(conecta.rs.getString("data"));
            jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));          
            jTextFieldHorario.setText(conecta.rs.getString("horario"));
            jTextField1log.setText(conecta.rs.getString("usuario"));
            jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
            jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
            jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao mostrar dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(true);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxCorreios.setEnabled(true);
          try {
              conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios");
            conecta.rs.last();
            jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
            jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
            jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
            jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
            jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
            jTextFieldData.setText(conecta.rs.getString("data"));
            jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));          
            jTextFieldHorario.setText(conecta.rs.getString("horario"));
            jTextField1log.setText(conecta.rs.getString("usuario"));
             jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
            jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
            jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao mostrar dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(true);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxCorreios.setEnabled(true);
          try {
              conecta.conectaBanco();
            conecta.rs.previous();
            jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
            jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
            jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
            jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
            jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
            jTextFieldData.setText(conecta.rs.getString("data"));
            jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));          
            jTextFieldHorario.setText(conecta.rs.getString("horario"));
            jTextField1log.setText(conecta.rs.getString("usuario"));
            jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
            jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
            jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
           conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Não existe anterior!");
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxRecebimento.setEnabled(false);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(true);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxCorreios.setEnabled(true);
           try {
               conecta.conectaBanco();
            conecta.rs.next();
            jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
            jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
            jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
            jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
            jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
            jTextFieldData.setText(conecta.rs.getString("data"));
            jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));          
            jTextFieldHorario.setText(conecta.rs.getString("horario"));
            jTextField1log.setText(conecta.rs.getString("usuario"));
            jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
            jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
            jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Não existe próximo!");
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        mod.setPesquisa(jTextFieldPesquisar.getText());
        Usuario model = buscaProduto(mod);
        jTextFieldCod.setText(String.valueOf(model.getId()));
        jTextFieldEmpresa.setText(model.getEmpresa());
        jTextFieldDescricao.setText(model.getDescricao());
        jComboBoxDestinatario.setSelectedItem(model.getDestinatario());
        jComboBoxDepartamento.setSelectedItem(model.getDepartamento());
        jTextFieldData.setText(model.getData());
        jTextFieldDataEntrega.setText(model.getDataentrega());
        jTextFieldHorario.setText(model.getHorario());
        jTextField1log.setText(model.getUsuario());
        jComboBoxEntrega.setSelectedItem(model.getEntrega());
        jComboBoxRecebimento.setSelectedItem(model.getRecebimento());
        jComboBoxCorreios.setSelectedItem(model.getCorreios());
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(true);
        jTextFieldDescricao.setEnabled(true);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(true);
        jComboBoxEntrega.setEnabled(true);
        jTextFieldDataEntrega.setEnabled(true);
        jTextFieldHorario.setEnabled(true);
        jComboBoxCorreios.setEditable(true);
        preenchertabela("select * from usuarios where data like '%" + jTextFieldPesquisar.getText() + "%' and Usuario ='" + jTextField1log.getText()+"'"); 
       
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTableEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableEstado.getValueAt(jTableEstado.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from usuarios where id='"+ id +"'");
        
        try {
        conecta.rs.first();
        jTextFieldCod.setText(String.valueOf(conecta.rs.getInt("id")));
        jTextFieldEmpresa.setText(conecta.rs.getString("empresa"));
        jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
        jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
        jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
        jTextFieldData.setText(conecta.rs.getString("data"));
        jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));
        jTextFieldHorario.setText(conecta.rs.getString("horario"));   
        jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
        jTextField1log.setText(conecta.rs.getString("usuario")); 
        jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
        jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
        jButtonAlterar.setEnabled(true);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jComboBoxDestinatario.setEnabled(true);
        jComboBoxDepartamento.setEnabled(true);
        jTextFieldData.setEnabled(false);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jComboBoxEntrega.setEnabled(true);
        jComboBoxCorreios.setEnabled(false);
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
        // JOptionPane.showMessageDialog(rootPane, empresa);
    }//GEN-LAST:event_jTableEstadoMouseClicked

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextField1logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1logActionPerformed

    private void jComboBoxRecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxRecebimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxRecebimentoActionPerformed

    private void jComboBoxDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDestinatarioActionPerformed
        // TODO add your handling code here:
        int posicao;
        
        posicao = jComboBoxDestinatario.getSelectedIndex();
        
        switch (posicao){
              case 1:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jTextFieldEmail.setText("antoniocarlos@asscont.com.br");
              jLabelsubject.setText("Novo Malote na recepção!");
              break;
              case 2:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jTextFieldEmail.setText("adriana@asscont.com.br");
              jLabelsubject.setText("Novo Malote Adriana, 24h para baixa!");
              break;
              case 3:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jComboBoxDepartamento.addItem("Fiscal");
              jTextFieldEmail.setText("acaxias@asscont.com.br");
              jLabelsubject.setText("Novo Malote Andreia, 24h para baixa!");
              break;
              case 4:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jTextFieldEmail.setText("bruno.lopes@asscont.com.br");
              jLabelsubject.setText("Novo Malote Bruno, 24h para baixa!");
              break;
              case 5:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jTextFieldEmail.setText("edilene@asscont.com.br");
              jLabelsubject.setText("Novo Malote Edilene, 24h para baixa!");
              break;
              case 6:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jComboBoxDepartamento.addItem("Fiscal");
              jTextFieldEmail.setText("");
              jLabelsubject.setText("");
              break;    
              case 7:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("jurídico");
              jTextFieldEmail.setText("");
              jLabelsubject.setText("");
              break;  
              case 8:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Contábil");
              jTextFieldEmail.setText("katia@asscont.com.br");
              jLabelsubject.setText("Novo Malote Katia, 24h para baixa!");
              break; 
              case 9:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("RH");
              jTextFieldEmail.setText("rh@asscont.com.br");
              jLabelsubject.setText("Novo Malote Louise, 24h para baixa!");
              break; 
              case 10:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("DP");
              jTextFieldEmail.setText("danielle.dp@asscont.com.br");
              jLabelsubject.setText("Novo Malote, 24h para baixa!");
              break; 
              case 11:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Declarações");
              jTextFieldEmail.setText("declaracoes@asscont.com.br");
              jLabelsubject.setText("Novo Malote Thais ou Rodrigo, 24h para baixa!");
              break; 
              case 12:
              jComboBoxDepartamento.removeAllItems();
              jComboBoxDepartamento.addItem("Financeiro");
              jTextFieldEmail.setText("vera@asscont.com.br");
              jLabelsubject.setText("Novo Malote Vera, 24h para baixa!");
              break;      
        }
    }//GEN-LAST:event_jComboBoxDestinatarioActionPerformed

    private void jComboBoxEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEntregaActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        jTextFieldCod.setText("");
        jTextFieldEmpresa.setText("");
        jTextFieldDescricao.setText("");
        jComboBoxDestinatario.setSelectedItem("Sem seleção");
        jComboBoxDepartamento.setSelectedItem("Sem seleção");
        jTextFieldData.setText("");
        jTextFieldDataEntrega.setText("");
        jTextFieldHorario.setText("");
        jComboBoxEntrega.setSelectedItem("Não entregue");
       // jTextField1log.setText("");
        jComboBoxRecebimento.setSelectedItem("Não recebido");
        jComboBoxCorreios.setSelectedItem("Malote");
        jButtonNovo.setEnabled(true);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jTextFieldEmpresa.setEnabled(false);
        jTextFieldDescricao.setEnabled(false);
        jComboBoxDestinatario.setEnabled(false);
        jComboBoxDepartamento.setEnabled(false);
        jTextFieldData.setEnabled(false);
        jTextFieldDataEntrega.setEnabled(false);
        jTextFieldHorario.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jComboBoxEntrega.setEnabled(false);
        jComboBoxCorreios.setEnabled(false);
        //preenchertabela("select * from usuarios order by id");
         preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
        
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jComboBoxDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDepartamentoActionPerformed

    private void jComboBoxCorreiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorreiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCorreiosActionPerformed

    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","EMPRESA","DESCRICAO","DESTINATARIO","DEPARTAMENTO","DATA","DATAENTREGA","HORARIO","ENTREGA","USUARIO","RECEBIMENTO","TIPO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("id"),conecta.rs.getString("empresa"),conecta.rs.getString("descricao"),conecta.rs.getString("destinatario"),conecta.rs.getString("departamento"),conecta.rs.getString("data"),conecta.rs.getString("dataentrega"),conecta.rs.getString("horario"),conecta.rs.getString("entrega"),conecta.rs.getString("usuario"),conecta.rs.getString("recebimento"),conecta.rs.getString("correio")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
       //     JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableEstado.setModel(modelo);
        jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableEstado.getColumnModel().getColumn(0).setResizable(false);
        jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(165);
        jTableEstado.getColumnModel().getColumn(1).setResizable(false);
        jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableEstado.getColumnModel().getColumn(2).setResizable(false);
        jTableEstado.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(3).setResizable(false);
        jTableEstado.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableEstado.getColumnModel().getColumn(4).setResizable(false);
        jTableEstado.getColumnModel().getColumn(5).setPreferredWidth(75);
        jTableEstado.getColumnModel().getColumn(5).setResizable(false);
        jTableEstado.getColumnModel().getColumn(6).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(6).setResizable(false);
        jTableEstado.getColumnModel().getColumn(7).setPreferredWidth(65);
        jTableEstado.getColumnModel().getColumn(7).setResizable(false);
        jTableEstado.getColumnModel().getColumn(8).setPreferredWidth(75);
        jTableEstado.getColumnModel().getColumn(8).setResizable(false);
        jTableEstado.getColumnModel().getColumn(9).setPreferredWidth(65);
        jTableEstado.getColumnModel().getColumn(9).setResizable(false);
        jTableEstado.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(10).setResizable(false);
        jTableEstado.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(11).setResizable(false);
        jTableEstado.getTableHeader().setReorderingAllowed(true);
        jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
        jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    public Usuario buscaProduto(Usuario modelo){
       conecta.conectaBanco();
       conecta.executaSQL("select * from usuarios where data like '%" + modelo.getPesquisa() + "%' and Usuario ='" + jTextField1log.getText()+"'");
       try  {
           conecta.rs.first();
            mod.setId(conecta.rs.getInt("id"));
            mod.setEmpresa(conecta.rs.getString("empresa"));
            mod.setDescricao(conecta.rs.getString("descricao"));
            mod.setDestinatario(conecta.rs.getString("destinatario"));
            mod.setDepartamento(conecta.rs.getString("departamento"));
            mod.setData(conecta.rs.getString("data"));
            mod.setDataentrega(conecta.rs.getString("dataentrega"));
            mod.setHorario(conecta.rs.getString("horario")); 
            mod.setEntrega(conecta.rs.getString("entrega"));
            mod.setRecebimento(conecta.rs.getString("recebimento"));
            mod.setCorreios(conecta.rs.getString("correio")); 
            mod.setUsuario(conecta.rs.getString("usuario"));  
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao buscar a data!\nErro" + ex);  
          // preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
       }
      
       return mod;
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JComboBox<String> jComboBoxCorreios;
    private javax.swing.JComboBox<String> jComboBoxDepartamento;
    private javax.swing.JComboBox<String> jComboBoxDestinatario;
    private javax.swing.JComboBox<String> jComboBoxEntrega;
    private javax.swing.JComboBox<String> jComboBoxRecebimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JTextField jLabelsubject;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField1log;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JFormattedTextField jTextFieldData;
    private javax.swing.JFormattedTextField jTextFieldDataEntrega;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldDiaBaixa;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEmpresa;
    private javax.swing.JFormattedTextField jTextFieldHorario;
    private javax.swing.JTextField jTextFieldHorarioBaixa;
    private javax.swing.JFormattedTextField jTextFieldPesquisar;
    // End of variables declaration//GEN-END:variables

    public void recebendo(String recebe){
        jTextField1log.setText(recebe);
    }
}
