/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;
import modelo.Usuario;

/**
 *
 * @author vinicius
 */
public class EntrevistaFinaliza extends javax.swing.JFrame {

    ConnectionConsulta conecta = new ConnectionConsulta();
    Usuario mod = new Usuario();
    ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    ControleLoginUsuario control = new ControleLoginUsuario();
    /**
     * Creates new form EntrevistaFinaliza
     */
    public EntrevistaFinaliza() {
        initComponents();
        conecta.conectaBanco();
        preenchertabela("select * from entrevistas order by idEntrevistas ");
        jTableEntrevista.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldParticipante = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCargo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCompareceu = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxCorrigiu = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxRetorno = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntrevista = new javax.swing.JTable();
        Alterar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextFieldData = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldHoras = new javax.swing.JTextField();
        jButtonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Participante:");

        jLabel2.setText("Data Entrevista:");

        jTextFieldParticipante.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldParticipanteKeyPressed(evt);
            }
        });

        jLabel3.setText("Horário Entrevista:");

        jLabel4.setText("Departamento:");

        jLabel5.setText("Cargo:");

        jLabel6.setText("Usuário:");

        jTextFieldUsuario.setEnabled(false);

        jLabel7.setText("Compareceu?");

        jComboBoxCompareceu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Sim ", "Não" }));

        jLabel8.setText("Corrigiu teste?");

        jComboBoxCorrigiu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Sim", "Não" }));

        jLabel9.setText("Retorno:");

        jComboBoxRetorno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sem seleção", "Sim", "Não" }));

        jTableEntrevista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEntrevista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEntrevistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEntrevista);

        Alterar.setText("Alterar");
        Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarActionPerformed(evt);
            }
        });

        jButton1.setText("Novo");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFieldData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDataKeyPressed(evt);
            }
        });

        jLabel10.setText("Id:");

        jTextFieldId.setEnabled(false);

        jTextFieldHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHorasActionPerformed(evt);
            }
        });

        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel7)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxCompareceu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(78, 78, 78)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxCorrigiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(59, 59, 59)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(Alterar)
                            .addGap(6, 6, 6)
                            .addComponent(jButtonReset))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(39, 39, 39)
                                    .addComponent(jLabel3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextFieldParticipante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jTextFieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxCompareceu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxCorrigiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxRetorno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addComponent(Alterar)
                    .addComponent(jButtonReset))
                .addGap(29, 29, 29)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1069, 724));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       // preenchertabela("select * from entrevistas where Usuario ='" + jTextFieldUsuario.getText()+"' order by idEntrevistas");
       preenchertabela("select * from entrevistas order by idEntrevistas ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldParticipanteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldParticipanteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldParticipante.getText());
            preenchertabela("select * from entrevistas where Participante like '%" + jTextFieldParticipante.getText() + "%' ");
            //and Usuario ='" + jTextFieldUsuario.getText()+"' 
        }
    }//GEN-LAST:event_jTextFieldParticipanteKeyPressed

    private void AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarActionPerformed
        // TODO add your handling code here:
         try {
            PreparedStatement pst = conecta.conn.prepareStatement("update entrevistas set Participante=?, Data=?, Horario=?, Departamento=?, Cargo=?, Compareceu=?, Corrigiu=?, Retorno=? where IdEntrevistas=?");
           
            pst.setString(1,jTextFieldParticipante.getText());
            pst.setString(2,jTextFieldData.getText());
            pst.setString(3,jTextFieldHoras.getText());
            pst.setString(4,jTextFieldDepartamento.getText());
            pst.setString(5,jTextFieldCargo.getText());     
            pst.setString(6, (String) jComboBoxCompareceu.getSelectedItem());
            pst.setString(7, (String) jComboBoxCorrigiu.getSelectedItem());
            pst.setString(8,(String) jComboBoxRetorno.getSelectedItem());
            pst.setInt(9,Integer.parseInt(jTextFieldId.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
           // preenchertabela("select * from entrevistas where Usuario ='" + jTextFieldUsuario.getText()+"' order by idEntrevistas ");
        preenchertabela("select * from entrevistas order by idEntrevistas ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }
    }//GEN-LAST:event_AlterarActionPerformed

    private void jTableEntrevistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEntrevistaMouseClicked
        // TODO add your handling code here:
        String IdEntrevistas = ""+jTableEntrevista.getValueAt(jTableEntrevista.getSelectedRow(), 0);
        conecta.conectaBanco();
        conecta.executaSQL("select * from entrevistas where IdEntrevistas='"+ IdEntrevistas +"'");
        
        try {
        conecta.rs.first();
        jTextFieldId.setText(String.valueOf(conecta.rs.getInt("IdEntrevistas")));
        jTextFieldParticipante.setText(conecta.rs.getString("Participante"));
        jTextFieldData.setText(conecta.rs.getString("Data"));
        jTextFieldHoras.setText(conecta.rs.getString("Horario"));
        jTextFieldDepartamento.setText(conecta.rs.getString("Departamento"));
        jTextFieldCargo.setText(conecta.rs.getString("Cargo"));   
        jTextFieldUsuario.setText(conecta.rs.getString("Usuario")); 
        jComboBoxCompareceu.setSelectedItem(conecta.rs.getString("Compareceu"));
        jComboBoxCorrigiu.setSelectedItem(conecta.rs.getString("Corrigiu"));
        jComboBoxRetorno.setSelectedItem(conecta.rs.getString("Retorno"));
        
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableEntrevistaMouseClicked

    private void jTextFieldHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHorasActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        //preenchertabela("select * from entrevistas where Usuario ='" + jTextFieldUsuario.getText()+"' order by idEntrevistas ");
        preenchertabela("select * from entrevistas order by idEntrevistas ");
        jTextFieldId.setText("");
        jTextFieldParticipante.setText("");
        jTextFieldData.setText("");
        jTextFieldHoras.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldCargo.setText("");
        jComboBoxCompareceu.setSelectedItem("Sem seleção");
        jComboBoxCorrigiu.setSelectedItem("Sem seleção");
        jComboBoxRetorno.setSelectedItem("Sem seleção");
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDataKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldParticipante.getText());
            preenchertabela("select * from entrevistas where Data like '%" + jTextFieldData.getText() + "%' ");
            //and Usuario ='" + jTextFieldUsuario.getText()+"'
        }
    }//GEN-LAST:event_jTextFieldDataKeyPressed

    
    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"ID","PARTICIPANTE","DATA","HORÁRIO","DEPARTAMENTO","CARGO","USUARIO","COMPARECEU","CORRIGIU","RETORNO"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getInt("idEntrevistas"),conecta.rs.getString("Participante"),conecta.rs.getString("Data"),conecta.rs.getString("Horario"),conecta.rs.getString("Departamento"),conecta.rs.getString("Cargo"),conecta.rs.getString("Usuario"),conecta.rs.getString("Compareceu"),conecta.rs.getString("Corrigiu"),conecta.rs.getString("Retorno")});
        }while(conecta.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableEntrevista.setModel(modelo);
        jTableEntrevista.getColumnModel().getColumn(0).setPreferredWidth(60);
        jTableEntrevista.getColumnModel().getColumn(0).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(1).setPreferredWidth(230);
        jTableEntrevista.getColumnModel().getColumn(1).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableEntrevista.getColumnModel().getColumn(2).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableEntrevista.getColumnModel().getColumn(3).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(4).setPreferredWidth(110);
        jTableEntrevista.getColumnModel().getColumn(4).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(5).setPreferredWidth(120);
        jTableEntrevista.getColumnModel().getColumn(5).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(6).setPreferredWidth(80);
        jTableEntrevista.getColumnModel().getColumn(6).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(7).setPreferredWidth(110);
        jTableEntrevista.getColumnModel().getColumn(7).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(8).setPreferredWidth(75);
        jTableEntrevista.getColumnModel().getColumn(8).setResizable(false);
        jTableEntrevista.getColumnModel().getColumn(9).setPreferredWidth(75);
        jTableEntrevista.getColumnModel().getColumn(9).setResizable(false);
        jTableEntrevista.getTableHeader().setReorderingAllowed(true);
        jTableEntrevista.setAutoResizeMode(jTableEntrevista.AUTO_RESIZE_OFF);
        jTableEntrevista.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EntrevistaFinaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EntrevistaFinaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EntrevistaFinaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EntrevistaFinaliza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EntrevistaFinaliza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxCompareceu;
    private javax.swing.JComboBox<String> jComboBoxCorrigiu;
    private javax.swing.JComboBox<String> jComboBoxRetorno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTableEntrevista;
    private javax.swing.JTextField jTextFieldCargo;
    private javax.swing.JTextField jTextFieldData;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldHoras;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldParticipante;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
public void recebendo(String recebe){
        jTextFieldUsuario.setText(recebe);
    }   
}
