/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class menuGerais extends javax.swing.JFrame {
    
    ConfirmacaoRecebimento enviarecebimento;
    EnvioMalote enviandomalote;
    ConnectionConsulta conecta = new ConnectionConsulta();
    /**
     * Creates new form menuGerais
     */
    public menuGerais(String userGerais) {
        initComponents();
        jLabelUserGerais.setText(userGerais);
    }

    private menuGerais() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel21 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jButtonVisualizarGrande = new javax.swing.JButton();
        jButtonRecebimentosGrande = new javax.swing.JButton();
        jButtonRecebimentosGrande1 = new javax.swing.JButton();
        jLabelUserGerais = new javax.swing.JLabel();
        jButtonVisualizarGrande1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Módulos gerais");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Receber documentos recepção");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Visualizar recebimentos recepção");

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Enviar documentos recepção");

        jButtonVisualizarGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search1.png"))); // NOI18N
        jButtonVisualizarGrande.setContentAreaFilled(false);
        jButtonVisualizarGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search grande.png"))); // NOI18N
        jButtonVisualizarGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search grande.png"))); // NOI18N
        jButtonVisualizarGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrandeActionPerformed(evt);
            }
        });

        jButtonRecebimentosGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder1.png"))); // NOI18N
        jButtonRecebimentosGrande.setBorder(null);
        jButtonRecebimentosGrande.setBorderPainted(false);
        jButtonRecebimentosGrande.setContentAreaFilled(false);
        jButtonRecebimentosGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecebimentosGrande.setFocusPainted(false);
        jButtonRecebimentosGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder grande.png"))); // NOI18N
        jButtonRecebimentosGrande.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder grande.png"))); // NOI18N
        jButtonRecebimentosGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecebimentosGrandeActionPerformed(evt);
            }
        });

        jButtonRecebimentosGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/envio pequeno.png"))); // NOI18N
        jButtonRecebimentosGrande1.setBorder(null);
        jButtonRecebimentosGrande1.setBorderPainted(false);
        jButtonRecebimentosGrande1.setContentAreaFilled(false);
        jButtonRecebimentosGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecebimentosGrande1.setFocusPainted(false);
        jButtonRecebimentosGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/envio grande.png"))); // NOI18N
        jButtonRecebimentosGrande1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/envio grande.png"))); // NOI18N
        jButtonRecebimentosGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecebimentosGrande1ActionPerformed(evt);
            }
        });

        jLabelUserGerais.setText("jLabel1");

        jButtonVisualizarGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/visualizar pequeno.png"))); // NOI18N
        jButtonVisualizarGrande1.setContentAreaFilled(false);
        jButtonVisualizarGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar Grande.png"))); // NOI18N
        jButtonVisualizarGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Visualizar Grande.png"))); // NOI18N
        jButtonVisualizarGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Visualizar envios recepção");

        jDesktopPane1.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRecebimentosGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonRecebimentosGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelUserGerais, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelUserGerais))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel21)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButtonRecebimentosGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonRecebimentosGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(219, 219, 219))))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jButtonVisualizarGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel2))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(jLabel4)))
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(226, 226, 226))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel5))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(jLabel29)))
                                .addGap(0, 149, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUserGerais)
                .addGap(2, 2, 2)
                .addComponent(jLabel21)
                .addGap(52, 52, 52)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRecebimentosGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRecebimentosGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonVisualizarGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(833, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizarGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrandeActionPerformed
        // TODO add your handling code here:
        new Visualizador().show();
    }//GEN-LAST:event_jButtonVisualizarGrandeActionPerformed

    private void jButtonRecebimentosGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecebimentosGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUserGerais.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Gestor"))||(conecta.rs.getString("permissao").equals("Recebedor")||(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao2").equals("Financeiro"))))){
                //                    ||(conecta.rs.getString("permissao").equals("Recebedor2"))||(conecta.rs.getString("permissao").equals("Recebedor3"))||(conecta.rs.getString("permissao").equals("Recebedor4"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor5"))||(conecta.rs.getString("permissao").equals("Recebedor6"))||(conecta.rs.getString("permissao").equals("Recebedor7"))||(conecta.rs.getString("permissao").equals("Recebedor8"))||(conecta.rs.getString("permissao").equals("Recebedor9"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor10"))||(conecta.rs.getString("permissao").equals("Recebedor11"))||(conecta.rs.getString("permissao").equals("Recebedor12"))||(conecta.rs.getString("permissao").equals("Recebedor13"))||(conecta.rs.getString("permissao").equals("Recebedor14"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor15"))||(conecta.rs.getString("permissao").equals("Recebedor16"))||(conecta.rs.getString("permissao").equals("Recebedor17"))||(conecta.rs.getString("permissao").equals("Recebedor18"))||(conecta.rs.getString("permissao").equals("Recebedor19"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor20"))||(conecta.rs.getString("permissao").equals("Recebedor21"))||(conecta.rs.getString("permissao").equals("Recebedor22"))||(conecta.rs.getString("permissao").equals("Recebedor23"))||(conecta.rs.getString("permissao").equals("Recebedor24"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor25")||(conecta.rs.getString("permissao").equals("Recebedor26"))||(conecta.rs.getString("permissao").equals("Recebedor27")))){
                enviarecebimento = new ConfirmacaoRecebimento();
                enviarecebimento.setVisible(true);
                enviarecebimento.setState(ConfirmacaoRecebimento.NORMAL);
                enviarecebimento.recebendo(jLabelUserGerais.getText());
                // ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
                //   Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonRecebimentosGrandeActionPerformed

    private void jButtonRecebimentosGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecebimentosGrande1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUserGerais.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Gestor"))||(conecta.rs.getString("permissao").equals("Recebedor")||(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao2").equals("Financeiro"))))){
                //                    ||(conecta.rs.getString("permissao").equals("Recebedor2"))||(conecta.rs.getString("permissao").equals("Recebedor3"))||(conecta.rs.getString("permissao").equals("Recebedor4"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor5"))||(conecta.rs.getString("permissao").equals("Recebedor6"))||(conecta.rs.getString("permissao").equals("Recebedor7"))||(conecta.rs.getString("permissao").equals("Recebedor8"))||(conecta.rs.getString("permissao").equals("Recebedor9"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor10"))||(conecta.rs.getString("permissao").equals("Recebedor11"))||(conecta.rs.getString("permissao").equals("Recebedor12"))||(conecta.rs.getString("permissao").equals("Recebedor13"))||(conecta.rs.getString("permissao").equals("Recebedor14"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor15"))||(conecta.rs.getString("permissao").equals("Recebedor16"))||(conecta.rs.getString("permissao").equals("Recebedor17"))||(conecta.rs.getString("permissao").equals("Recebedor18"))||(conecta.rs.getString("permissao").equals("Recebedor19"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor20"))||(conecta.rs.getString("permissao").equals("Recebedor21"))||(conecta.rs.getString("permissao").equals("Recebedor22"))||(conecta.rs.getString("permissao").equals("Recebedor23"))||(conecta.rs.getString("permissao").equals("Recebedor24"))
                //            ||(conecta.rs.getString("permissao").equals("Recebedor25")||(conecta.rs.getString("permissao").equals("Recebedor26"))||(conecta.rs.getString("permissao").equals("Recebedor27")))){
                enviandomalote = new EnvioMalote();
                enviandomalote.setVisible(true);
                enviandomalote.setState(ConfirmacaoRecebimento.NORMAL);
                enviandomalote.recebendo(jLabelUserGerais.getText());
                // ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
                //   Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonRecebimentosGrande1ActionPerformed

    private void jButtonVisualizarGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande1ActionPerformed
        // TODO add your handling code here:
        new VisualizadorEnvio().show();
    }//GEN-LAST:event_jButtonVisualizarGrande1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGerais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGerais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRecebimentosGrande;
    private javax.swing.JButton jButtonRecebimentosGrande1;
    private javax.swing.JButton jButtonVisualizarGrande;
    private javax.swing.JButton jButtonVisualizarGrande1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelUserGerais;
    // End of variables declaration//GEN-END:variables
}
