/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.AtualizaDia;
import controle.AtualizadoHora;
import controle.ConnectionConsulta;
import controle.ControleLoginUsuario;
import controle.conectar;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import static java.lang.System.exit;
import java.net.URI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.Timer;
import modelo.ModeloLoginUsuario;
import modelo.ModeloTabela;
import modelo.Usuario;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.TimerTask;

/**
 *
 * @author vinicius
 */
public class Menu extends javax.swing.JFrame {
    Consultador enviatexto;
    ConfirmacaoRecebimento enviarecebimento;
    EnvioMalote enviandomalote;
    AgendarReuniao enviareuniao;
    EnvioEmail enviaEmail;
    CriarProjeto agendaentre;
    EntrevistaFinaliza finalizaentre;
    AgendaLigacoes ligacaofinal;
    CancelaReuniao enviasenha;
    NovoTesteJanela recebesenhaa;
    ConsultaLigacoes recebeauto;
    AgendaTelefonica recebeautoo;
    ConfirmacaoRecebimentoRecepcao recepcaoreceb;
    ConnectionConsulta conecta = new ConnectionConsulta();
    //Usuario mod = new Usuario();
    //ModeloLoginUsuario modelo = new ModeloLoginUsuario();
    //ControleLoginUsuario control = new ControleLoginUsuario();
    /**
     * Creates new form Menu
     */
    public Menu(String user) {
        initComponents();
        //conecta.conectaBanco();
        jLabelUser.setText(user);
        this.setExtendedState(this.getExtendedState()|Menu.MAXIMIZED_BOTH);
        setIcon();
        AtualizadoHora.start(jLabelHorario);  
        AtualizaDia.start(jLabelDia);
//        onlineChat();
        
       
        //conecta.conectaBanco();
      preenchertabela("select * from chatglobal order by id desc ");
             //   conecta.desconecta(); 
             
            
             
         
    }
        
    

    Menu() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
//    public void onlineChat (){
//            Statement st=null;
//            ResultSet rs=null;
//            conecta.conectaBanco();
//        Connection minhaconexao = conectar.GetConnection();
//            try{
//                
//                st = (Statement)minhaconexao.createStatement();                   
//                rs=st.executeQuery("SELECT nome from login where Status = 0 order by nome");
//                
//                while(rs.next()){
//                    String nome =rs.getString("nome");
//                    jComboBoxOnline.addItem(nome);
//                          
//            }
//     //    conecta.desconecta();
//        }catch(Exception e){
//}
//}  


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButtonSairGrande = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableChat = new javax.swing.JTable();
        jTextFieldChat = new javax.swing.JTextField();
        jButtonEnvio = new javax.swing.JButton();
        jLabelHorario = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jComboBoxOnline = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVisualizar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Visualizar = new javax.swing.JMenu();
        Cadastrar = new javax.swing.JMenuItem();
        Visualizador = new javax.swing.JMenuItem();
        CadastroUsuario = new javax.swing.JMenuItem();
        Recebimento = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");

        jDesktopPane1.setBackground(new java.awt.Color(240, 240, 240));
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(1024, 768));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Olá:");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alterar.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel15.setText("Alterar Senha");

        jButtonSairGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close1.png"))); // NOI18N
        jButtonSairGrande.setBorder(null);
        jButtonSairGrande.setBorderPainted(false);
        jButtonSairGrande.setContentAreaFilled(false);
        jButtonSairGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSairGrande.setFocusPainted(false);
        jButtonSairGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close grande.png"))); // NOI18N
        jButtonSairGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close grande.png"))); // NOI18N
        jButtonSairGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairGrandeActionPerformed(evt);
            }
        });

        jLabel14.setText("Logoff");

        jLabelUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUser.setText("jLabel1");

        jTableChat.setAutoCreateRowSorter(true);
        jTableChat.setForeground(new java.awt.Color(0, 51, 255));
        jTableChat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableChat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableChatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableChat);

        jTextFieldChat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldChatKeyPressed(evt);
            }
        });

        jButtonEnvio.setText("Enviar");
        jButtonEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnvioActionPerformed(evt);
            }
        });

        jLabelHorario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHorario.setText("jLabel30");

        jLabelDia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDia.setText("jLabel30");

        jComboBoxOnline.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxOnlineItemStateChanged(evt);
            }
        });

        jButton3.setText("Ver online");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Recepção pequeno.png"))); // NOI18N
        jButton5.setText("Modulos Recepção       ");
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Recepção.png"))); // NOI18N
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Recepção.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/RH.png"))); // NOI18N
        jButton1.setText("Módulos RH                    ");
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/RH grande.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/RH grande.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/juridico pequeno.png"))); // NOI18N
        jButton6.setText("Módulos  jurídico           ");
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Juridico.png"))); // NOI18N
        jButton6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Juridico.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerais pequeno.png"))); // NOI18N
        jButton7.setText("Fluxo de documentos");
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerais.png"))); // NOI18N
        jButton7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gerais.png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gestores pequeno.png"))); // NOI18N
        jButton8.setText("Módulos gestores       ");
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gestores.png"))); // NOI18N
        jButton8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Gestores.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/contabil pequeno.png"))); // NOI18N
        jButton9.setText("Módulos Contábil         ");
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Contabil.png"))); // NOI18N
        jButton9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Contabil.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fiscal pequeno.png"))); // NOI18N
        jButton10.setText("Módulos Fiscal             ");
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fiscal.png"))); // NOI18N
        jButton10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Fiscal.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pessoal pequeno.png"))); // NOI18N
        jButton11.setText("Modulos pessoal           ");
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pessoal.png"))); // NOI18N
        jButton11.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pessoal.png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(new java.awt.Color(255, 255, 255));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Declarações pequeno.png"))); // NOI18N
        jButton12.setText("Módulos Declarações  ");
        jButton12.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Declarações.png"))); // NOI18N
        jButton12.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Declarações.png"))); // NOI18N
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Financeiro pequeno.png"))); // NOI18N
        jButton13.setText("Módulos Financeiro      ");
        jButton13.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Financeiro.png"))); // NOI18N
        jButton13.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Financeiro.png"))); // NOI18N
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Chat Global");

        jTextAreaVisualizar.setEditable(false);
        jTextAreaVisualizar.setColumns(20);
        jTextAreaVisualizar.setLineWrap(true);
        jTextAreaVisualizar.setRows(5);
        jTextAreaVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextAreaVisualizar);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Visualizador");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Outubro rosa.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setText("Outubro rosa");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Nuvem.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Supote.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setText("Nuvem");

        jLabel9.setText("Chamado");

        jLabel10.setText("Ajuda");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/duvida.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonSairGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelUser, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jTextFieldChat, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonEnvio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelHorario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelDia, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jComboBoxOnline, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                .addGap(88, 88, 88)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabelHorario)
                        .addGap(62, 62, 62)
                        .addComponent(jLabelDia)
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelUser, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jLabel2))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jButtonSairGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(21, 21, 21))
                                        .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                    .addGap(8, 8, 8)
                                                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27))))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                        .addComponent(jButton4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                                                        .addComponent(jButton3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBoxOnline, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                        .addComponent(jTextFieldChat)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButtonEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jLabel3))
                                        .addGap(12, 12, 12))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2)
                                        .addGap(14, 14, 14)))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(jLabel9)))
                                .addGap(7, 7, 7)))
                        .addGap(66, 66, 66)))
                .addGap(96, 96, 96))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldChat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonEnvio)
                                    .addComponent(jButton4)))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSairGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3))
                                .addGap(7, 7, 7)
                                .addComponent(jLabel3)
                                .addGap(7, 7, 7)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelUser)
                            .addComponent(jLabel1)
                            .addComponent(jLabelHorario)
                            .addComponent(jLabelDia)))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Visualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user_menu.png"))); // NOI18N
        Visualizar.setText("Controle");
        Visualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizarActionPerformed(evt);
            }
        });

        Cadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        Cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/plus.png"))); // NOI18N
        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        Visualizar.add(Cadastrar);

        Visualizador.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        Visualizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/search.png"))); // NOI18N
        Visualizador.setText("Visualizar");
        Visualizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualizadorActionPerformed(evt);
            }
        });
        Visualizar.add(Visualizador);

        CadastroUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        CadastroUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list nano.png"))); // NOI18N
        CadastroUsuario.setText("Cadastro  de usuário");
        CadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastroUsuarioActionPerformed(evt);
            }
        });
        Visualizar.add(CadastroUsuario);

        Recebimento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        Recebimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/folder.png"))); // NOI18N
        Recebimento.setText("Recebimentos");
        Recebimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebimentoActionPerformed(evt);
            }
        });
        Visualizar.add(Recebimento);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario verde pequeno.png"))); // NOI18N
        jMenuItem12.setText("Agenda");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        Visualizar.add(jMenuItem12);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/xml nano.png"))); // NOI18N
        jMenuItem13.setText("Leitor xml");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        Visualizar.add(jMenuItem13);

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/close.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Visualizar.add(Sair);

        jMenuBar2.add(Visualizar);

        jMenu6.setText("Relatórios");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem1.setText("Relatório padrão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem2.setText("Relatório não recebido");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pdf.png"))); // NOI18N
        jMenuItem4.setText("Relatório resumido");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem4);

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar.png"))); // NOI18N
        jMenuItem6.setText("Criar reunião");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar cancel.png"))); // NOI18N
        jMenuItem7.setText("Cancelar Reunião");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar consulta.png"))); // NOI18N
        jMenuItem5.setText("Consulta Reunião");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem5);

        jMenuBar2.add(jMenu6);

        jMenu8.setText("E-mail");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_menu.png"))); // NOI18N
        jMenuItem3.setText("E-mail");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem3);

        jMenuBar2.add(jMenu8);

        jMenu9.setText("Entrevistas");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user pequeno.png"))); // NOI18N
        jMenuItem8.setText("Agendar Entrevista");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem8);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user pequeno user.png"))); // NOI18N
        jMenuItem9.setText("Finalizar Entrevista");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem9);

        jMenuBar2.add(jMenu9);

        jMenu10.setText("Ligações");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call pequeno aten.png"))); // NOI18N
        jMenuItem10.setText("Registrar Ligações");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call pequeno visuali.png"))); // NOI18N
        jMenuItem11.setText("Consultar ligações");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuItem11);

        jMenuBar2.add(jMenu10);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1164, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1180, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VisualizarActionPerformed

    private void VisualizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizadorActionPerformed
        new Visualizador().show();
    }//GEN-LAST:event_VisualizadorActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed

try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviatexto = new Consultador();
         enviatexto.setVisible(true);
         enviatexto.setState(Consultador.NORMAL);
         enviatexto.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
//        try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Comum")){
//            Consultador Cl = new Consultador();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }   
    }//GEN-LAST:event_CadastrarActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
           try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update login set Status = 0 where login='"+jLabelUser.getText()+"'");
            pst.execute();
            //   JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
            // preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }

        
        
          Login Cl = new Login();
          Cl.setVisible(true);
         // Runtime.getRuntime().exit(0);
          dispose();
//        Login Cl = new Login();
//        Cl.setVisible(true);
//        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void CadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastroUsuarioActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor"))){
            CadastroLogin Cl = new CadastroLogin();
            Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }   
    }//GEN-LAST:event_CadastroUsuarioActionPerformed

    private void RecebimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebimentoActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Gestor"))||(conecta.rs.getString("permissao").equals("Recebedor")||(conecta.rs.getString("permissao").equals("Admin")))){ 
//            if((conecta.rs.getString("permissao").equals("Recebedor"))||(conecta.rs.getString("permissao").equals("Recebedor1"))||(conecta.rs.getString("permissao").equals("Recebedor2"))||(conecta.rs.getString("permissao").equals("Recebedor3"))||(conecta.rs.getString("permissao").equals("Recebedor4"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor5"))||(conecta.rs.getString("permissao").equals("Recebedor6"))||(conecta.rs.getString("permissao").equals("Recebedor7"))||(conecta.rs.getString("permissao").equals("Recebedor8"))||(conecta.rs.getString("permissao").equals("Recebedor9"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor10"))||(conecta.rs.getString("permissao").equals("Recebedor11"))||(conecta.rs.getString("permissao").equals("Recebedor12"))||(conecta.rs.getString("permissao").equals("Recebedor13"))||(conecta.rs.getString("permissao").equals("Recebedor14"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor15"))||(conecta.rs.getString("permissao").equals("Recebedor16"))||(conecta.rs.getString("permissao").equals("Recebedor17"))||(conecta.rs.getString("permissao").equals("Recebedor18"))||(conecta.rs.getString("permissao").equals("Recebedor19"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor20"))||(conecta.rs.getString("permissao").equals("Recebedor21"))||(conecta.rs.getString("permissao").equals("Recebedor22"))||(conecta.rs.getString("permissao").equals("Recebedor23"))||(conecta.rs.getString("permissao").equals("Recebedor24"))
//            ||(conecta.rs.getString("permissao").equals("Recebedor25"))||(conecta.rs.getString("permissao").equals("Recebedor26")||(conecta.rs.getString("permissao").equals("Recebedor27")))){
                enviarecebimento = new ConfirmacaoRecebimento();
                enviarecebimento.setVisible(true);
                enviarecebimento.setState(ConfirmacaoRecebimento.NORMAL);
                enviarecebimento.recebendo(jLabelUser.getText());
               // ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
             //   Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }       
//         try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Recebedor9")){
//            ConfirmacaoRecebimento Cl = new ConfirmacaoRecebimento();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }   
    }//GEN-LAST:event_RecebimentoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios order by data");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2017\\E\\Citrix\\Matriz ireport\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios where recebimento in ('Não recebido') order by departamento");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2017\\E\\Citrix\\Matriz ireport não\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
             try {
                 conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
             if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
//               Consultador Cl = new Consultador();
//               Cl.setVisible(true);
         enviaEmail = new EnvioEmail();
         enviaEmail.setVisible(true);
         enviaEmail.setState(Consultador.NORMAL);
         enviaEmail.recebendo(jLabelUser.getText());
               
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
             conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }    
             
             
             
//        try {
//            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
//            conecta.rs.first();
//            if(conecta.rs.getString("permissao").equals("Comum")){
//            EnvioEmail Cl = new EnvioEmail();
//            Cl.setVisible(true);
//            }else{
//                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//            }
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
//        }  




    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        try{
            conecta.conectaBanco();
            conecta.executaSQL("select * from usuarios where destinatario = 'TDP' and recebimento = 'Não recebido' order by id");
            JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2017\\E\\Citrix\\Matriz ireport\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
            JasperViewer jv = new JasperViewer(jpPrint,false);
            jv.setVisible(true);
            jv.toFront();
            conecta.desconecta();
        }catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
         
//            try{
//            conecta.executaSQL("select * from reuniao order by SUBSTR( datainicio, 7,4),SUBSTR( datainicio, 4,2),SUBSTR( datainicio, 1,2)");
//        JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
//            JasperPrint jpPrint = JasperFillManager.fillReport("\\\\hp2011\\E\\Citrix\\Matriz reuniao\\ireport\\RelatorioCadastros.jasper", new HashMap(), relatResul);
//            JasperViewer jv = new JasperViewer(jpPrint,false);
//            jv.setVisible(true);
//            jv.toFront();
//        }catch (JRException ex) {
//            JOptionPane.showMessageDialog(rootPane,"Erro ao chamar o relatório!\nErro:"+ ex);
//        }

           try {
               conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebesenhaa= new NovoTesteJanela();
         recebesenhaa.setVisible(true);
         recebesenhaa.setState(NovoTesteJanela.NORMAL);
         recebesenhaa.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
          //  NovoTesteJanela Cl = new NovoTesteJanela();
           //   Cl.setVisible(true);  
            
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviareuniao = new AgendarReuniao();
         enviareuniao.setVisible(true);
         enviareuniao.setState(AgendarReuniao.NORMAL);
         enviareuniao.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        //AgendarReuniao Cl = new AgendarReuniao();
           //  Cl.setVisible(true); 
              
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         enviasenha = new CancelaReuniao();
         enviasenha.setVisible(true);
         enviasenha.setState(CancelaReuniao.NORMAL);
         enviasenha.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         agendaentre = new CriarProjeto();
         agendaentre.setVisible(true);
         agendaentre.setState(CriarProjeto.NORMAL);
         agendaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
         try {
             conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         finalizaentre = new EntrevistaFinaliza();
         finalizaentre.setVisible(true);
         finalizaentre.setState(EntrevistaFinaliza.NORMAL);
         finalizaentre.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch 
                (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
           if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         ligacaofinal = new AgendaLigacoes();
         ligacaofinal.setVisible(true);
         ligacaofinal.setState(AgendaLigacoes.NORMAL);
         ligacaofinal.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
           conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        //AgendaLigacoes Cl = new AgendaLigacoes();
          //    Cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
         conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
         conecta.rs.first();           
         if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Financeiro"))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebeauto = new ConsultaLigacoes();
         recebeauto.setVisible(true);
         recebeauto.setState(ConsultaLigacoes.NORMAL);
         recebeauto.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
         conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
       // ConsultaLigacoes Cl = new ConsultaLigacoes();
       //       Cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
         try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            conecta.rs.first();           
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Gestor"))){
             //  Consultador Cl = new Consultador();
            //   Cl.setVisible(true);
         recebeautoo = new AgendaTelefonica();
         recebeautoo.setVisible(true);
         recebeautoo.setState(AgendaTelefonica.NORMAL);
         recebeautoo.recebendo(jLabelUser.getText()); 
         
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
         new LeitorXml().show();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        menuRecepcao crm = new menuRecepcao(jLabelUser.getText());
        crm.setVisible(true);
        // this.dispose();
        //try {
            //conecta.conectaBanco();
            //    PreparedStatement pst = conecta.conn.prepareStatement("update login set Status = 1 where login='"+jTextFieldUsuario.getText()+"'");
            //     pst.execute();
            // JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
            // preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        preenchertabela("select * from chatglobal order by id desc ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // if(evt.getStateChange () == ItemEvent.SELECTED) {
            Statement st=null;
            ResultSet rs=null;
            Connection minhaconexao = conectar.GetConnection();
            conecta.conectaBanco();
            try{
                jComboBoxOnline.removeAllItems();
                st = (Statement)minhaconexao.createStatement();
                rs=st.executeQuery("SELECT nome from login where Status = '1' order by nome");

                while(rs.next()){
                    String nome =rs.getString("nome");
                    jComboBoxOnline.addItem(nome);

                }
                //    conecta.desconecta();
            }catch(Exception e){
            }
            //}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxOnlineItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxOnlineItemStateChanged
        // TODO add your handling code here:
        //  if(evt.getStateChange () == ItemEvent.SELECTED) {
            //  conecta.conectaBanco();
            // preenchertabela("select nome from login where Status ='1' order by nome ASC");

            //  conecta.desconecta();
            //   }

        //        if(evt.getStateChange () == ItemEvent.SELECTED) {
            //            Statement st=null;
            //            ResultSet rs=null;
            //            Connection minhaconexao = conectar.GetConnection();
            //             conecta.conectaBanco();
            //            try{
                //
                //                st = (Statement)minhaconexao.createStatement();
                //                rs=st.executeQuery("SELECT nome from login where Status = 0 order by nome");
                //
                //                while(rs.next()){
                    //                    String nome =rs.getString("nome");
                    //                    jComboBoxOnline.addItem(nome);
                    //
                    //            }
                //     //    conecta.desconecta();
                //        }catch(Exception e){
                //}
            //        }

    }//GEN-LAST:event_jComboBoxOnlineItemStateChanged

    private void jButtonEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnvioActionPerformed
        // TODO add your handling code here:
        if(jTextFieldChat.getText().equals("")){JOptionPane.showMessageDialog(null,"Preencha algo!");}
        else{
            try{
                conecta.conectaBanco();
                PreparedStatement pst = conecta.conn.prepareStatement("insert into chatglobal (texto,usuario,data,horario)values (?,?,?,?)");
                pst.setString(1,jTextFieldChat.getText());
                pst.setString(2,jLabelUser.getText());
                pst.setString(3,jLabelDia.getText());
                pst.setString(4,jLabelHorario.getText());
                pst.executeUpdate();
                // JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
                preenchertabela("select * from chatglobal order by id desc ");
                conecta.desconecta();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
            }
            jTextFieldChat.setText("");
        }

    }//GEN-LAST:event_jButtonEnvioActionPerformed

    private void jTextFieldChatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldChatKeyPressed
        // TODO add your handling code here:
        if(jTextFieldChat.getText().equals("") && (evt.getKeyCode() == KeyEvent.VK_ENTER)){JOptionPane.showMessageDialog(null,"Preencha algo!");}
        else{
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                try{
                    conecta.conectaBanco();
                    PreparedStatement pst = conecta.conn.prepareStatement("insert into chatglobal (texto,usuario,data,horario)values (?,?,?,?)");
                    pst.setString(1,jTextFieldChat.getText());
                    pst.setString(2,jLabelUser.getText());
                    pst.setString(3,jLabelDia.getText());
                    pst.setString(4,jLabelHorario.getText());
                    pst.executeUpdate();
                    // JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso");
                    preenchertabela("select * from chatglobal order by id desc ");
                    conecta.desconecta();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane,"Erro na Inserção!\n Erro: "+ex);
                }
                jTextFieldChat.setText("");
            }
        }

    }//GEN-LAST:event_jTextFieldChatKeyPressed

    private void jButtonSairGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            PreparedStatement pst = conecta.conn.prepareStatement("update login set Status = 0 where login='"+jLabelUser.getText()+"'");
            pst.execute();
            //   JOptionPane.showMessageDialog(rootPane,"Alterado com sucesso");
            //preenchertabela("select * from usuarios order by id");
            // preenchertabela("select * from usuarios where Usuario ='" + jTextField1log.getText()+"' order by id ");
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao alterar!\n Erro: "+ex);
        }

        
        
          Login Cl = new Login();
          Cl.setVisible(true);
         // Runtime.getRuntime().exit(0);
          dispose();
        
        
//        new java.util.Timer().schedule( 
//        new java.util.TimerTask() {
//            @Override
//            public void run() {

             //dispose(); //pode ser o visible(false), caso queira chama-lo alguma outra hora do jeito que estava
//            Login frameNovo = new Login();
//            frameNovo.setSize(500,500);
//           frameNovo.setVisible(true);
//
//           }
//       }, 
//        5000 //tempo = 5 segundos
//);
    }//GEN-LAST:event_jButtonSairGrandeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CadastroDeUsuario frm = new CadastroDeUsuario(jLabelUser.getText());
        frm.setVisible(true);
        //new CadastroDeUsuario().show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        menuRh rrm = new menuRh(jLabelUser.getText());
        rrm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        menuJuridico jrm = new menuJuridico(jLabelUser.getText());
        jrm.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        menuGerais grm = new menuGerais(jLabelUser.getText());
        grm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        menuGestores germ = new menuGestores(jLabelUser.getText());
        germ.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        menuFiscal fisrm = new menuFiscal(jLabelUser.getText());
        fisrm.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        menuFinanceiro firm = new menuFinanceiro(jLabelUser.getText());
        firm.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        menuPessoal perm = new menuPessoal(jLabelUser.getText());
        perm.setVisible(true);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
       // if (menuContabil != null) {
        menuContabil conrm = new menuContabil(jLabelUser.getText());
        conrm.setVisible(true);
        // }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        menuDeclaracoes derm = new menuDeclaracoes(jLabelUser.getText());
        derm.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jTableChatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableChatMouseClicked
        // TODO add your handling code here:
        String id = ""+jTableChat.getValueAt(jTableChat.getSelectedRow(), 4);
        conecta.conectaBanco();
        conecta.executaSQL("select * from chatglobal where id='"+ id +"'");
        
        try {
        conecta.rs.first();
        //jTextFieldId.setText(String.valueOf(conecta.rs.getInt("id")));
        jTextAreaVisualizar.setText(conecta.rs.getString("texto"));
//        jTextFieldDescricao.setText(conecta.rs.getString("descricao"));
//        jComboBoxDestinatario.setSelectedItem(conecta.rs.getString("destinatario"));
//        jComboBoxDepartamento.setSelectedItem(conecta.rs.getString("departamento"));
//        jTextFieldData.setText(conecta.rs.getString("data"));
//        jTextFieldDataEntrega.setText(conecta.rs.getString("dataentrega"));
//        jTextFieldHorario.setText(conecta.rs.getString("horario"));   
//        jComboBoxEntrega.setSelectedItem(conecta.rs.getString("entrega"));
//        jTextField1log.setText(conecta.rs.getString("usuario")); 
//        jComboBoxRecebimento.setSelectedItem(conecta.rs.getString("recebimento"));
//        jComboBoxCorreios.setSelectedItem(conecta.rs.getString("correio"));
        conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao selecionar os dados!\n Erro: "+ex);
        }
    }//GEN-LAST:event_jTableChatMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:          
        try{
            URI link = new URI("http://www.inca.gov.br/outubro-rosa/outubro-rosa.asp");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        try{
            URI link = new URI("http://192.168.16.153/");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        try{
            URI link = new URI("http://192.168.16.251/ocomon");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        try{
            URI link = new URI("http://192.168.16.153/public.php?service=files&t=ae49a655e5b5bb64fac9b056a7f97a69");
            Desktop.getDesktop().browse(link);
        }catch(Exception erro){
            System.out.println(erro);
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    
    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"TEXTO","USUARIO","DATA","HORARIO","ID"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first();      
        do{
          dados.add(new Object[]{conecta.rs.getString("texto"),conecta.rs.getString("usuario"),conecta.rs.getString("data"),conecta.rs.getString("horario"),conecta.rs.getString("id")});
        }while(conecta.rs.next());
        conecta.desconecta();
        } catch (SQLException ex) {
       //     JOptionPane.showMessageDialog(null, "Não existe dados cadastrados!");
       
        }
        
      
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableChat.setModel(modelo);
        jTableChat.getColumnModel().getColumn(0).setPreferredWidth(400);
        jTableChat.getColumnModel().getColumn(0).setResizable(false);
        jTableChat.getColumnModel().getColumn(1).setPreferredWidth(80);
        jTableChat.getColumnModel().getColumn(1).setResizable(false);
        jTableChat.getColumnModel().getColumn(2).setPreferredWidth(80);
        jTableChat.getColumnModel().getColumn(2).setResizable(false);
        jTableChat.getColumnModel().getColumn(3).setPreferredWidth(80);
        jTableChat.getColumnModel().getColumn(3).setResizable(false);  
        jTableChat.getColumnModel().getColumn(4).setPreferredWidth(40);
        jTableChat.getColumnModel().getColumn(4).setResizable(false);
        jTableChat.getTableHeader().setReorderingAllowed(true);
        jTableChat.setAutoResizeMode(jTableChat.AUTO_RESIZE_OFF);
        jTableChat.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
    }
    
    /**
     * @param args the command line arguments
     * C://Users/marilialc/Documents/NetBeansProjects/MinhaAplicacao/ireport
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Cadastrar;
    private javax.swing.JMenuItem CadastroUsuario;
    private javax.swing.JMenuItem Recebimento;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenuItem Visualizador;
    private javax.swing.JMenu Visualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonEnvio;
    private javax.swing.JButton jButtonSairGrande;
    private javax.swing.JComboBox<String> jComboBoxOnline;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHorario;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableChat;
    private javax.swing.JTextArea jTextAreaVisualizar;
    private javax.swing.JTextField jTextFieldChat;
    // End of variables declaration//GEN-END:variables
   private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }
    
    
}
