/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class menuRh extends javax.swing.JFrame {

    CriarProjeto agendaentre;
    EntrevistaFinaliza finalizaentre;
    ConnectionConsulta conecta = new ConnectionConsulta();
    /**
     * Creates new form menuRh
     */
    public menuRh(String userRh) {
        initComponents();
        jLabelUsuario.setText(userRh);
    }

    private menuRh() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonVisualizarGrande1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonVisualizarGrande2 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonVisualizarGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user medio.png"))); // NOI18N
        jButtonVisualizarGrande1.setContentAreaFilled(false);
        jButtonVisualizarGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonVisualizarGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user grande user.png"))); // NOI18N
        jButtonVisualizarGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Agendar Entrevista");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("Finalizar Entrevistas");

        jButtonVisualizarGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user atualizar medio.png"))); // NOI18N
        jButtonVisualizarGrande2.setContentAreaFilled(false);
        jButtonVisualizarGrande2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user atualizar grande.png"))); // NOI18N
        jButtonVisualizarGrande2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user atualizar grande.png"))); // NOI18N
        jButtonVisualizarGrande2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande2ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Módulos Recursos humanos");

        jLabelUsuario.setText("jLabel1");

        jDesktopPane1.setLayer(jButtonVisualizarGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(jButtonVisualizarGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(310, 310, 310)
                        .addComponent(jLabelUsuario)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288))))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel18)
                        .addGap(99, 99, 99)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonVisualizarGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVisualizarGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(822, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVisualizarGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                agendaentre = new CriarProjeto();
                agendaentre.setVisible(true);
                agendaentre.setState(CriarProjeto.NORMAL);
                agendaentre.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande1ActionPerformed

    private void jButtonVisualizarGrande2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande2ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                finalizaentre = new EntrevistaFinaliza();
                finalizaentre.setVisible(true);
                finalizaentre.setState(EntrevistaFinaliza.NORMAL);
                finalizaentre.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuRh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuRh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuRh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuRh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuRh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVisualizarGrande1;
    private javax.swing.JButton jButtonVisualizarGrande2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
