/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class menuGestores extends javax.swing.JFrame {
    
    CancelaReuniao enviasenha;
    NovoTesteJanela recebesenhaa;
    AgendarReuniao enviareuniao;
    ConnectionConsulta conecta = new ConnectionConsulta();

    /**
     * Creates new form menuGestores
     */
    public menuGestores(String userGes) {
        initComponents();
        jLabelGestores.setText(userGes);
    }

    private menuGestores() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonCadastroUsuarioGrande1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabelGestores = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCadastroUsuarioGrande1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.setBorder(null);
        jButtonCadastroUsuarioGrande1.setBorderPainted(false);
        jButtonCadastroUsuarioGrande1.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande1.setFocusPainted(false);
        jButtonCadastroUsuarioGrande1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar Grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("Agendar Reunião");

        jButtonCadastroUsuarioGrande2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.setBorder(null);
        jButtonCadastroUsuarioGrande2.setBorderPainted(false);
        jButtonCadastroUsuarioGrande2.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande2.setFocusPainted(false);
        jButtonCadastroUsuarioGrande2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar grande cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar grande cancel.png"))); // NOI18N
        jButtonCadastroUsuarioGrande2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("Cancelar Reunião");

        jButtonCadastroUsuarioGrande3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar medio consulta.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.setBorder(null);
        jButtonCadastroUsuarioGrande3.setBorderPainted(false);
        jButtonCadastroUsuarioGrande3.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande3.setFocusPainted(false);
        jButtonCadastroUsuarioGrande3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendar pesquisa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("Visualizar Reuniões");

        jButtonCadastroUsuarioGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list pequeno.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.setBorder(null);
        jButtonCadastroUsuarioGrande.setBorderPainted(false);
        jButtonCadastroUsuarioGrande.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande.setFocusPainted(false);
        jButtonCadastroUsuarioGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/list grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrandeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("Criar Novo Usuário");

        jLabelGestores.setText("jLabel1");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Módulos gestores");

        jButtonCadastroUsuarioGrande4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastroempresa pequeno.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.setBorder(null);
        jButtonCadastroUsuarioGrande4.setBorderPainted(false);
        jButtonCadastroUsuarioGrande4.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande4.setFocusPainted(false);
        jButtonCadastroUsuarioGrande4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastroempresa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastroempresa grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("Cadastro Empresas");

        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelGestores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelGestores)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jButtonCadastroUsuarioGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonCadastroUsuarioGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonCadastroUsuarioGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jButtonCadastroUsuarioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonCadastroUsuarioGrande4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGestores)
                .addGap(104, 104, 104)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastroUsuarioGrande4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel7))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadastroUsuarioGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroUsuarioGrande2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroUsuarioGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadastroUsuarioGrande1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(795, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroUsuarioGrande3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande3ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelGestores.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                recebesenhaa= new NovoTesteJanela();
                recebesenhaa.setVisible(true);
                recebesenhaa.setState(NovoTesteJanela.NORMAL);
                recebesenhaa.recebendo(jLabelGestores.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        //NovoTesteJanela Cl = new NovoTesteJanela();
        // Cl.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande3ActionPerformed

    private void jButtonCadastroUsuarioGrande2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande2ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelGestores.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                enviasenha = new CancelaReuniao();
                enviasenha.setVisible(true);
                enviasenha.setState(CancelaReuniao.NORMAL);
                enviasenha.recebendo(jLabelGestores.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }

        // CancelaReuniao Cl = new CancelaReuniao();
        //      Cl.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande2ActionPerformed

    private void jButtonCadastroUsuarioGrande1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelGestores.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                enviareuniao = new AgendarReuniao();
                enviareuniao.setVisible(true);
                enviareuniao.setState(AgendarReuniao.NORMAL);
                enviareuniao.recebendo(jLabelGestores.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }

        //AgendarReuniao Cl = new AgendarReuniao();
        //  Cl.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande1ActionPerformed

    private void jButtonCadastroUsuarioGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelGestores.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor"))){
                CadastroLogin Cl = new CadastroLogin();
                Cl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonCadastroUsuarioGrandeActionPerformed

    private void jButtonCadastroUsuarioGrande4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande4ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelGestores.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor"))){
                cadastroEmpresa Tl = new cadastroEmpresa();
                Tl.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuGestores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuGestores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroUsuarioGrande;
    private javax.swing.JButton jButtonCadastroUsuarioGrande1;
    private javax.swing.JButton jButtonCadastroUsuarioGrande2;
    private javax.swing.JButton jButtonCadastroUsuarioGrande3;
    private javax.swing.JButton jButtonCadastroUsuarioGrande4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelGestores;
    // End of variables declaration//GEN-END:variables
}
