/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ConnectionConsulta;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author vinicius
 */
public class menuRecepcao extends javax.swing.JFrame {
    
    Consultador enviatexto;        
    EnvioEmail enviaEmail;
    AgendaLigacoes ligacaofinal;   
    AgendaTelefonica recebeautoo;
    ConfirmacaoRecebimentoRecepcao recepcaoreceb;
    ConnectionConsulta conecta = new ConnectionConsulta();

    /**
     * Creates new form menuRecepcao
     */
    public menuRecepcao(String userrh) {
        initComponents();
        jLabelUsuario.setText(userrh);
    }

    private menuRecepcao() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonCadastrarGrande = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadastroUsuarioGrande4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jButtonVisualizarGrande3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButtonVisualizarGrande6 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        jButtonCadastrarGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add.png"))); // NOI18N
        jButtonCadastrarGrande.setBorder(null);
        jButtonCadastrarGrande.setBorderPainted(false);
        jButtonCadastrarGrande.setContentAreaFilled(false);
        jButtonCadastrarGrande.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarGrande.setFocusPainted(false);
        jButtonCadastrarGrande.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add grande.png"))); // NOI18N
        jButtonCadastrarGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/add grande.png"))); // NOI18N
        jButtonCadastrarGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarGrandeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Cadastro de Documentos");

        jButtonCadastroUsuarioGrande4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario verde medio.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.setBorder(null);
        jButtonCadastroUsuarioGrande4.setBorderPainted(false);
        jButtonCadastroUsuarioGrande4.setContentAreaFilled(false);
        jButtonCadastroUsuarioGrande4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastroUsuarioGrande4.setFocusPainted(false);
        jButtonCadastroUsuarioGrande4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario verde grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/calendario verde grande.png"))); // NOI18N
        jButtonCadastroUsuarioGrande4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroUsuarioGrande4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("Agenda telefônica");

        jButtonVisualizarGrande3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Registro.png"))); // NOI18N
        jButtonVisualizarGrande3.setContentAreaFilled(false);
        jButtonVisualizarGrande3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Consultar.png"))); // NOI18N
        jButtonVisualizarGrande3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/phone-call Consultar.png"))); // NOI18N
        jButtonVisualizarGrande3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande3ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("Registrar ligações");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_botao.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_grande.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/mail_grande.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("E-mail solicitação baixa");

        jButtonVisualizarGrande6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/recebe pequeno.png"))); // NOI18N
        jButtonVisualizarGrande6.setContentAreaFilled(false);
        jButtonVisualizarGrande6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVisualizarGrande6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/recebe grande.png"))); // NOI18N
        jButtonVisualizarGrande6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/recebe grande.png"))); // NOI18N
        jButtonVisualizarGrande6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVisualizarGrande6ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel28.setText("Receber Documentos");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Módulos Recepção");

        jLabelUsuario.setText("jLabel1");

        jDesktopPane1.setLayer(jButtonCadastrarGrande, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonCadastroUsuarioGrande4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jButtonVisualizarGrande6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabelUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(322, 322, 322)
                        .addComponent(jLabelUsuario))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addComponent(jButtonCadastrarGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel3))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jButtonVisualizarGrande6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(145, 145, 145)
                                        .addComponent(jButtonCadastroUsuarioGrande4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(112, 112, 112)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                        .addGap(131, 131, 131)
                                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jButtonVisualizarGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addGap(72, 72, 72)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabel17))
                .addGap(50, 50, 50)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonCadastroUsuarioGrande4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarGrande3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVisualizarGrande6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(822, 406));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroUsuarioGrande4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroUsuarioGrande4ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))||(conecta.rs.getString("permissao").equals("Gestor"))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                recebeautoo = new AgendaTelefonica();
                recebeautoo.setVisible(true);
                recebeautoo.setState(AgendaTelefonica.NORMAL);
                recebeautoo.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonCadastroUsuarioGrande4ActionPerformed

    private void jButtonVisualizarGrande3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande3ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                ligacaofinal = new AgendaLigacoes();
                ligacaofinal.setVisible(true);
                ligacaofinal.setState(AgendaLigacoes.NORMAL);
                ligacaofinal.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Gestor")||(conecta.rs.getString("permissao").equals("Recepção"))))){
                //               Consultador Cl = new Consultador();
                //               Cl.setVisible(true);
                enviaEmail = new EnvioEmail();
                enviaEmail.setVisible(true);
                enviaEmail.setState(Consultador.NORMAL);
                enviaEmail.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
        //        try {
            //            conecta.executaSQL("select * from login where login='"+jLabelUser.getText()+"'");
            //            conecta.rs.first();
            //            if(conecta.rs.getString("permissao").equals("Comum")){
                //                EnvioEmail Cl = new EnvioEmail();
                //                Cl.setVisible(true);
                //            }else{
                //                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
                //            }
            //        } catch (SQLException ex) {
            //            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            //        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonCadastrarGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarGrandeActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin"))||(conecta.rs.getString("permissao").equals("Recepção"))){
                //               Consultador Cl = new Consultador();
                //               Cl.setVisible(true);
                enviatexto = new Consultador();
                enviatexto.setVisible(true);
                enviatexto.setState(Consultador.NORMAL);
                enviatexto.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }

        //        if(enviatexto == null){
            //         enviatexto = new Consultador();
            //        enviatexto.setVisible(true);
            //        enviatexto.recebendo(jLabelUser.getText());
            //        }else{
            //         enviatexto.setVisible(true);
            //         enviatexto.setState(Consultador.NORMAL);
            //         enviatexto.recebendo(jLabelUser.getText());
            //        }
    }//GEN-LAST:event_jButtonCadastrarGrandeActionPerformed

    private void jButtonVisualizarGrande6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVisualizarGrande6ActionPerformed
        // TODO add your handling code here:
        try {
            conecta.conectaBanco();
            conecta.executaSQL("select * from login where login='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if((conecta.rs.getString("permissao").equals("Admin")||(conecta.rs.getString("permissao").equals("Recepção")))){
                //  Consultador Cl = new Consultador();
                //   Cl.setVisible(true);
                recepcaoreceb = new ConfirmacaoRecebimentoRecepcao();
                recepcaoreceb.setVisible(true);
                recepcaoreceb.setState(ConfirmacaoRecebimentoRecepcao.NORMAL);
                recepcaoreceb.recebendo(jLabelUsuario.getText());

            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
            }
            conecta.desconecta();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Você não possui permissão para acessar este módulo!");
        }
    }//GEN-LAST:event_jButtonVisualizarGrande6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuRecepcao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuRecepcao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCadastrarGrande;
    private javax.swing.JButton jButtonCadastroUsuarioGrande4;
    private javax.swing.JButton jButtonVisualizarGrande3;
    private javax.swing.JButton jButtonVisualizarGrande6;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelUsuario;
    // End of variables declaration//GEN-END:variables
}
