/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import visao.*;
import controle.ConnectionConsulta;
import java.awt.Desktop;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableRowSorter;
import modelo.ModeloTabela;
import modelo.Usuario;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelo.ModeloTabela;
import modelo.Usuario;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;



/**
 *
 * @author vinicius
 */
public class VisualizadorEnvio extends javax.swing.JFrame {
    
     private final String ruta = System.getProperties().getProperty("user.dir");
      ConnectionConsulta conecta = new ConnectionConsulta();
      Usuario mod = new Usuario();
    /**
     * Creates new form VisualizadoreEx
     */
    public VisualizadorEnvio() {
        initComponents();
        this.setExtendedState(this.getExtendedState()|VisualizadorEnvio.MAXIMIZED_BOTH);
        conecta.conectaBanco();
        preenchertabela("select * from enviorecepcao");
       // preenchertabela("select * from usuarios where destinatario != 'AC'");
        jTableEstado.setAutoCreateRowSorter(true);
        //ModeloTabela modelo = (ModeloTabela) jTableEstado.getModel();
       //jTableEstado.setRowSorter(new TableRowSorter(modelo)); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldPesquisar2 = new javax.swing.JTextField();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jTextFieldPesquisar3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        Reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableEstado.setOpaque(false);
        jScrollPane2.setViewportView(jTableEstado);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        jPanel2.setOpaque(false);

        jTextFieldPesquisar2.setToolTipText("Empresa");
        jTextFieldPesquisar2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisar2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisar2KeyReleased(evt);
            }
        });

        jTextFieldPesquisar.setToolTipText("Descrição");
        jTextFieldPesquisar.setPreferredSize(new java.awt.Dimension(9, 20));
        jTextFieldPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisarActionPerformed(evt);
            }
        });
        jTextFieldPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarKeyReleased(evt);
            }
        });

        jTextFieldPesquisar3.setToolTipText("Destinatário");
        jTextFieldPesquisar3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisar3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisar3KeyReleased(evt);
            }
        });

        jTextField4.setToolTipText("Data Entrega");
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });

        jTextField6.setToolTipText("Horário");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel1.setText("Empresas:");

        jLabel2.setText("Descrições:");

        jLabel3.setText("Destinatário:");

        jLabel4.setText("Data:");

        jLabel5.setText("Data Entrega:");

        jLabel7.setText("Horário:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/xls.png"))); // NOI18N
        jButton1.setText("Criar Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jProgressBar1.setStringPainted(true);

        Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/user3.png"))); // NOI18N
        Reset.setToolTipText("Resetar");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(385, 385, 385)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldPesquisar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(311, 311, 311))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGap(122, 122, 122)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldPesquisar3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7))
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Reset, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{

            Thread t = new Thread(){
                public void run(){
                    XSSFWorkbook workbook = new XSSFWorkbook();
                    XSSFSheet hoja = workbook.createSheet();

                    XSSFRow fila = hoja.createRow(0);
                    fila.createCell(0).setCellValue("DATA");
                    fila.createCell(1).setCellValue("PROTOCOLO");
                    fila.createCell(2).setCellValue("EMPRESA");
                    fila.createCell(3).setCellValue("DESCRICAO");
                    fila.createCell(4).setCellValue("OBSERVAÇÃO");
                    fila.createCell(5).setCellValue("DESTINATARIO");
                    fila.createCell(6).setCellValue("DEPARTAMENTO");
                    fila.createCell(7).setCellValue("TIPO");
                    fila.createCell(8).setCellValue("DATA ENTREGA");
                    fila.createCell(9).setCellValue("HORÁRIO");
                    fila.createCell(10).setCellValue("RECEBIMENTO");
                    fila.createCell(11).setCellValue("ENTREGA");
                    fila.createCell(12).setCellValue("USUÁRIO");                    
                    fila.createCell(13).setCellValue("BAIXA");
                    fila.createCell(14).setCellValue("DIA BAIXA");
                    fila.createCell(15).setCellValue("HORARIOBAIXA");
                    fila.createCell(16).setCellValue("ID");
                    jProgressBar1.setMaximum(jTableEstado.getRowCount());
                    XSSFRow filas;
                    Rectangle rect;
                    for(int i=0; i<jTableEstado.getRowCount(); i++){

                        rect = jTableEstado.getCellRect(i, 0, true);
                        try{
                            jTableEstado.scrollRectToVisible(rect);
                        }catch(java.lang.ClassCastException e){}
                        jTableEstado.setRowSelectionInterval(i, i);
                        jProgressBar1.setValue((i+1));

                        filas = hoja.createRow((i+1));
                        filas.createCell(0).setCellValue(jTableEstado.getValueAt(i, 0).toString());
                        filas.createCell(1).setCellValue(jTableEstado.getValueAt(i, 1).toString());
                        filas.createCell(2).setCellValue(jTableEstado.getValueAt(i, 2).toString());
                        filas.createCell(3).setCellValue(jTableEstado.getValueAt(i, 3).toString());
                        filas.createCell(4).setCellValue(jTableEstado.getValueAt(i, 4).toString());
                        filas.createCell(5).setCellValue(jTableEstado.getValueAt(i, 5).toString());
                        filas.createCell(6).setCellValue(jTableEstado.getValueAt(i, 6).toString());
                        filas.createCell(7).setCellValue(jTableEstado.getValueAt(i, 7).toString());
                        filas.createCell(8).setCellValue(jTableEstado.getValueAt(i, 8).toString());
                        filas.createCell(9).setCellValue(jTableEstado.getValueAt(i, 9).toString());
                        filas.createCell(10).setCellValue(jTableEstado.getValueAt(i, 10).toString());
                        filas.createCell(11).setCellValue(jTableEstado.getValueAt(i, 11).toString());
                        filas.createCell(12).setCellValue(jTableEstado.getValueAt(i, 12).toString());
                        filas.createCell(13).setCellValue(jTableEstado.getValueAt(i, 13).toString());
                        filas.createCell(14).setCellValue(jTableEstado.getValueAt(i, 14).toString());
                        filas.createCell(15).setCellValue(jTableEstado.getValueAt(i, 15).toString());
                        filas.createCell(16).setCellValue(jTableEstado.getValueAt(i, 16).toString());
                        // try{
                            //           Thread.sleep(20);
                            //      } catch (InterruptedException ex){
                            //         Logger.getLogger(Visualizador.class.getName ()).log(Level.SEVERE, null, ex);
                            //     }
                    }
                    jProgressBar1.setValue(0);
                    //jProgressBar1.setString("Abrindo Excel...");
                    //this.dispose();
                    //dispose();
                    try{
                        workbook.write(new FileOutputStream(new File(ruta+"//Excel.xlsx")));
                        Desktop.getDesktop().open(new File(ruta+"//Excel.xlsx"));
                    } catch (Exception ex) {
                        Logger.getLogger(VisualizadorEnvio.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            };
            t.start();
        }catch(Exception e){JOptionPane.showMessageDialog(null, e);}
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField1.getText());
            preenchertabela("select * from enviorecepcao where data like '%" + jTextField1.getText() + "%'");
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        jTextFieldPesquisar2.setText("");
        jTextFieldPesquisar.setText("");
        jTextFieldPesquisar3.setText("");
        jTextField1.setText("");
        jTextField4.setText("");
        jTextField6.setText("");
        preenchertabela("select * from enviorecepcao");
    }//GEN-LAST:event_ResetActionPerformed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField6.getText());
            preenchertabela("select * from enviorecepcao where horario like '%" + jTextField6.getText() + "%'");
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField4.getText());
            preenchertabela("select * from enviorecepcao where dataentrega like '%" + jTextField4.getText() + "%'");
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextFieldPesquisar3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar3.getText());
            preenchertabela("select * from enviorecepcao where destinatario like '%" + jTextFieldPesquisar3.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldPesquisar3KeyPressed

    private void jTextFieldPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar.getText());
            preenchertabela("select * from enviorecepcao where descricao like '%" + jTextFieldPesquisar.getText() + "%'");
            //conecta.desconecta();
        }
    }//GEN-LAST:event_jTextFieldPesquisarKeyPressed

    private void jTextFieldPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesquisarActionPerformed

    private void jTextFieldPesquisar2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar2.getText());
            preenchertabela("select * from enviorecepcao where empresa like '%" + jTextFieldPesquisar2.getText() + "%'");
        }
    }//GEN-LAST:event_jTextFieldPesquisar2KeyPressed

    private void jTextFieldPesquisar2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar2KeyReleased
        // TODO add your handling code here:
      //  if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar2.getText());
            preenchertabela("select * from enviorecepcao where empresa like '%" + jTextFieldPesquisar2.getText() + "%'");
       // }
    }//GEN-LAST:event_jTextFieldPesquisar2KeyReleased

    private void jTextFieldPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarKeyReleased
        // TODO add your handling code here:
      //   if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar.getText());
            preenchertabela("select * from enviorecepcao where descricao like '%" + jTextFieldPesquisar.getText() + "%'");
            //conecta.desconecta();
      // }
    }//GEN-LAST:event_jTextFieldPesquisarKeyReleased

    private void jTextFieldPesquisar3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisar3KeyReleased
        // TODO add your handling code here:
      //   if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextFieldPesquisar3.getText());
            preenchertabela("select * from enviorecepcao where destinatario like '%" + jTextFieldPesquisar3.getText() + "%'");
     //   }
    }//GEN-LAST:event_jTextFieldPesquisar3KeyReleased

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        // if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField1.getText());
            preenchertabela("select * from enviorecepcao where data like '%" + jTextField1.getText() + "%'");
       // }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        // TODO add your handling code here:
     //   if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField4.getText());
            preenchertabela("select * from enviorecepcao where dataentrega like '%" + jTextField4.getText() + "%'");
       // }
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
       //  if(evt.getKeyCode() == KeyEvent.VK_ENTER){

            mod.setPesquisa(jTextField6.getText());
            preenchertabela("select * from enviorecepcao where horario like '%" + jTextField6.getText() + "%'");
       // }
    }//GEN-LAST:event_jTextField6KeyReleased

    
    public void preenchertabela(String SQL){
        ArrayList dados = new ArrayList();
        
        
        String [] Colunas = new String[]{"DATA","PROTOCOLO","EMPRESA","DESCRICAO","OBSERVAÇÃO","DESTINATARIO","DEPARTAMENTO","TIPO","DATAENTREGA","HORARIO","RECEBIMENTO","ENTREGA","USUARIO","BAIXA","DIABAIXA","HORARIOBAIXA","DIAEDITADO","HORAEDITADO","ID"};
        conecta.conectaBanco();
        conecta.executaSQL(SQL);
        try {
           conecta.rs.first(); 
        do{
        dados.add(new Object[]{conecta.rs.getString("data"),conecta.rs.getString("protocolo"),conecta.rs.getString("empresa"),conecta.rs.getString("descricao"),conecta.rs.getString("Observação"),conecta.rs.getString("destinatario"),conecta.rs.getString("departamento"),conecta.rs.getString("tipo"),conecta.rs.getString("dataentrega"),conecta.rs.getString("horario"),conecta.rs.getString("recebimento"),conecta.rs.getString("entrega"),conecta.rs.getString("usuario"),conecta.rs.getString("baixa"),conecta.rs.getString("diabaixa"),conecta.rs.getString("horariobaixa"),conecta.rs.getString("diaatualização"),conecta.rs.getString("horarioatualização"),conecta.rs.getInt("id")}); 
        }while(conecta.rs.next());
        } catch (SQLException ex) {
        //    JOptionPane.showMessageDialog(null, "Pesquisa inexistente!");
        }             
        
        ModeloTabela modelo = new ModeloTabela(dados, Colunas);
        jTableEstado.setModel(modelo);
        jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(75);
        jTableEstado.getColumnModel().getColumn(0).setResizable(false);
        jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(180);
        jTableEstado.getColumnModel().getColumn(1).setResizable(false);
        jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(400);
        jTableEstado.getColumnModel().getColumn(2).setResizable(false);
        jTableEstado.getColumnModel().getColumn(3).setPreferredWidth(400);
        jTableEstado.getColumnModel().getColumn(3).setResizable(false);
        jTableEstado.getColumnModel().getColumn(4).setPreferredWidth(400);
        jTableEstado.getColumnModel().getColumn(4).setResizable(false);
        jTableEstado.getColumnModel().getColumn(5).setPreferredWidth(110);
        jTableEstado.getColumnModel().getColumn(5).setResizable(false);
        jTableEstado.getColumnModel().getColumn(6).setPreferredWidth(110);
        jTableEstado.getColumnModel().getColumn(6).setResizable(false);
        jTableEstado.getColumnModel().getColumn(7).setPreferredWidth(66);
        jTableEstado.getColumnModel().getColumn(7).setResizable(false);
        jTableEstado.getColumnModel().getColumn(8).setPreferredWidth(98);
        jTableEstado.getColumnModel().getColumn(8).setResizable(false);
        jTableEstado.getColumnModel().getColumn(9).setPreferredWidth(65);
        jTableEstado.getColumnModel().getColumn(9).setResizable(false);
        jTableEstado.getColumnModel().getColumn(10).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(10).setResizable(false);
        jTableEstado.getColumnModel().getColumn(11).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(11).setResizable(false);
        jTableEstado.getColumnModel().getColumn(12).setPreferredWidth(75);
        jTableEstado.getColumnModel().getColumn(12).setResizable(false);
        jTableEstado.getColumnModel().getColumn(13).setPreferredWidth(80);
        jTableEstado.getColumnModel().getColumn(13).setResizable(false);
        jTableEstado.getColumnModel().getColumn(14).setPreferredWidth(80);
        jTableEstado.getColumnModel().getColumn(14).setResizable(false);
        jTableEstado.getColumnModel().getColumn(15).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(15).setResizable(false);
        jTableEstado.getColumnModel().getColumn(16).setPreferredWidth(95);
        jTableEstado.getColumnModel().getColumn(16).setResizable(false);
        jTableEstado.getColumnModel().getColumn(17).setPreferredWidth(100);
        jTableEstado.getColumnModel().getColumn(17).setResizable(false);
        jTableEstado.getColumnModel().getColumn(18).setPreferredWidth(80);
        jTableEstado.getColumnModel().getColumn(18).setResizable(false);
        jTableEstado.getTableHeader().setReorderingAllowed(true);
        jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
        jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);       
        
    }
    /*
    public Usuario buscaProduto(Usuario modelo){
       conecta.conectaBanco();
       conecta.executaSQL("select * from usuarios where descricao like '%" + modelo.getPesquisa() + "%'");
       try  {
           conecta.rs.first();
            mod.setId(conecta.rs.getInt("id"));
            mod.setEmpresa(conecta.rs.getString("empresa"));
            mod.setDescricao(conecta.rs.getString("descricao"));
            mod.setDestinatario(conecta.rs.getString("destinatario"));
            mod.setDepartamento(conecta.rs.getString("departamento"));
            mod.setData(conecta.rs.getString("data"));
            mod.setDataentrega(conecta.rs.getString("dataentrega"));
            mod.setHorario(conecta.rs.getString("horario")); 
            mod.setEntrega(conecta.rs.getString("entrega"));
            mod.setUsuario(conecta.rs.getString("usuario"));
            mod.setRecebimento(conecta.rs.getString("recebimento"));
            mod.setCorreios(conecta.rs.getString("correio")); 
            mod.setBaixa(conecta.rs.getString("baixa"));
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao buscar a data!\nErro" + ex);   
       }
   
       return mod;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizadorEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizadorEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizadorEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizadorEnvio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizadorEnvio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Reset;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldPesquisar2;
    private javax.swing.JTextField jTextFieldPesquisar3;
    // End of variables declaration//GEN-END:variables
}
